// backend/sqlc/db.go
// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"database/sql"
)

// ======================================================================
// DBTX Interface
// ======================================================================

// DBTX is the database interface used by sqlc.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// ======================================================================
= Queries
// ======================================================================

// Queries provides all database queries.
type Queries struct {
	db DBTX
}

// New creates a new Queries instance.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// WithTx returns a new Queries instance with a transaction.
func (q *Queries) WithTx(tx *sql.Tx) *Queries {
	return &Queries{db: tx}
}

// ======================================================================
= User Queries
// ======================================================================

// CreateUserParams are the parameters for creating a user.
type CreateUserParams struct {
	ID          string
	Username    string
	Email       string
	PasswordHash string
	FullName    string
	Bio         string
	AvatarURL   string
	BannerURL   string
	Location    string
	Website     string
	Role        string
	Status      string
	IsVerified  bool
	IsPrivate   bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// CreateUser inserts a new user.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	query := `
		INSERT INTO users (
			id, username, email, password_hash, full_name, bio,
			avatar_url, banner_url, location, website, role, status,
			is_verified, is_private, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.Username, arg.Email, arg.PasswordHash, arg.FullName, arg.Bio,
		arg.AvatarURL, arg.BannerURL, arg.Location, arg.Website,
		arg.Role, arg.Status, arg.IsVerified, arg.IsPrivate,
		arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

// GetUserByID retrieves a user by ID.
func (q *Queries) GetUserByID(ctx context.Context, id string) (*User, error) {
	query := `SELECT * FROM users WHERE id = $1 AND deleted_at IS NULL`
	var u User
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&u.ID, &u.Username, &u.Email, &u.PasswordHash, &u.FullName,
		&u.Bio, &u.AvatarURL, &u.BannerURL, &u.Location, &u.Website,
		&u.Role, &u.Status, &u.IsVerified, &u.IsPrivate,
		&u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

// GetUserByUsername retrieves a user by username.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	query := `SELECT * FROM users WHERE username = $1 AND deleted_at IS NULL`
	var u User
	err := q.db.QueryRowContext(ctx, query, username).Scan(
		&u.ID, &u.Username, &u.Email, &u.PasswordHash, &u.FullName,
		&u.Bio, &u.AvatarURL, &u.BannerURL, &u.Location, &u.Website,
		&u.Role, &u.Status, &u.IsVerified, &u.IsPrivate,
		&u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

// GetUserByEmail retrieves a user by email.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	query := `SELECT * FROM users WHERE email = $1 AND deleted_at IS NULL`
	var u User
	err := q.db.QueryRowContext(ctx, query, email).Scan(
		&u.ID, &u.Username, &u.Email, &u.PasswordHash, &u.FullName,
		&u.Bio, &u.AvatarURL, &u.BannerURL, &u.Location, &u.Website,
		&u.Role, &u.Status, &u.IsVerified, &u.IsPrivate,
		&u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

// GetUserByUsernameOrEmail retrieves a user by either username or email.
func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, identifier string) (*User, error) {
	query := `SELECT * FROM users WHERE (username = $1 OR email = $2) AND deleted_at IS NULL`
	var u User
	err := q.db.QueryRowContext(ctx, query, identifier, identifier).Scan(
		&u.ID, &u.Username, &u.Email, &u.PasswordHash, &u.FullName,
		&u.Bio, &u.AvatarURL, &u.BannerURL, &u.Location, &u.Website,
		&u.Role, &u.Status, &u.IsVerified, &u.IsPrivate,
		&u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
	)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

// ListUsersParams are the parameters for listing users.
type ListUsersParams struct {
	Limit  int32
	Offset int32
	SortBy string
	Order  string
}

// ListUsers returns a paginated list of users.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*User, error) {
	query := fmt.Sprintf(`SELECT * FROM users WHERE deleted_at IS NULL ORDER BY %s %s LIMIT $1 OFFSET $2`, arg.SortBy, arg.Order)
	rows, err := q.db.QueryContext(ctx, query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var users []*User
	for rows.Next() {
		var u User
		if err := rows.Scan(
			&u.ID, &u.Username, &u.Email, &u.PasswordHash, &u.FullName,
			&u.Bio, &u.AvatarURL, &u.BannerURL, &u.Location, &u.Website,
			&u.Role, &u.Status, &u.IsVerified, &u.IsPrivate,
			&u.CreatedAt, &u.UpdatedAt, &u.DeletedAt,
		); err != nil {
			return nil, err
		}
		users = append(users, &u)
	}
	return users, rows.Err()
}

// CountUsers returns the total number of users.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	query := `SELECT COUNT(*) FROM users WHERE deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query).Scan(&count)
	return count, err
}

// UpdateUser updates a user.
func (q *Queries) UpdateUser(ctx context.Context, arg User) error {
	query := `
		UPDATE users SET
			username = $1, email = $2, password_hash = $3, full_name = $4,
			bio = $5, avatar_url = $6, banner_url = $7, location = $8,
			website = $9, role = $10, status = $11, is_verified = $12,
			is_private = $13, updated_at = $14
		WHERE id = $15 AND deleted_at IS NULL
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.Username, arg.Email, arg.PasswordHash, arg.FullName,
		arg.Bio, arg.AvatarURL, arg.BannerURL, arg.Location,
		arg.Website, arg.Role, arg.Status, arg.IsVerified,
		arg.IsPrivate, arg.UpdatedAt, arg.ID,
	)
	return err
}

// SoftDeleteUser soft deletes a user.
func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	query := `UPDATE users SET deleted_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// HardDeleteUser permanently deletes a user.
func (q *Queries) HardDeleteUser(ctx context.Context, id string) error {
	query := `DELETE FROM users WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// ======================================================================
= Tweet Queries
// ======================================================================

// CreateTweetParams are the parameters for creating a tweet.
type CreateTweetParams struct {
	ID          string
	UserID      string
	Content     string
	MediaURLs   []string
	ParentTweetID *string
	RetweetOfID   *string
	IsPoll      bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

// CreateTweet inserts a new tweet.
func (q *Queries) CreateTweet(ctx context.Context, arg CreateTweetParams) error {
	query := `
		INSERT INTO tweets (
			id, user_id, content, media_urls, parent_tweet_id,
			retweet_of_id, is_poll, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.UserID, arg.Content, pq.Array(arg.MediaURLs),
		arg.ParentTweetID, arg.RetweetOfID, arg.IsPoll,
		arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

// GetTweetByID retrieves a tweet by ID.
func (q *Queries) GetTweetByID(ctx context.Context, id string) (*Tweet, error) {
	query := `SELECT * FROM tweets WHERE id = $1 AND deleted_at IS NULL`
	var t Tweet
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&t.ID, &t.UserID, &t.Content, pq.Array(&t.MediaURLs),
		&t.ParentTweetID, &t.RetweetOfID, &t.IsPoll,
		&t.CreatedAt, &t.UpdatedAt, &t.DeletedAt,
	)
	if err != nil {
		return nil, err
	}
	return &t, nil
}

// ListTweetsByUserID returns tweets by a user.
func (q *Queries) ListTweetsByUserID(ctx context.Context, userID string, limit int32, offset int32) ([]*Tweet, error) {
	query := `SELECT * FROM tweets WHERE user_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*Tweet
	for rows.Next() {
		var t Tweet
		if err := rows.Scan(
			&t.ID, &t.UserID, &t.Content, pq.Array(&t.MediaURLs),
			&t.ParentTweetID, &t.RetweetOfID, &t.IsPoll,
			&t.CreatedAt, &t.UpdatedAt, &t.DeletedAt,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &t)
	}
	return tweets, rows.Err()
}

// GetFeedTweets returns tweets from followed users.
func (q *Queries) GetFeedTweets(ctx context.Context, userIDs []string, limit int32, cursor string) ([]*Tweet, error) {
	// Build IN clause
	query := fmt.Sprintf(`
		SELECT * FROM tweets
		WHERE user_id IN (%s) AND deleted_at IS NULL
		ORDER BY created_at DESC LIMIT $1
	`, strings.Join(pq.Array(userIDs), ","))
	rows, err := q.db.QueryContext(ctx, query, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*Tweet
	for rows.Next() {
		var t Tweet
		if err := rows.Scan(
			&t.ID, &t.UserID, &t.Content, pq.Array(&t.MediaURLs),
			&t.ParentTweetID, &t.RetweetOfID, &t.IsPoll,
			&t.CreatedAt, &t.UpdatedAt, &t.DeletedAt,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &t)
	}
	return tweets, rows.Err()
}

// CountTweetsByUserID counts tweets by user.
func (q *Queries) CountTweetsByUserID(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM tweets WHERE user_id = $1 AND deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// SoftDeleteTweet soft deletes a tweet.
func (q *Queries) SoftDeleteTweet(ctx context.Context, id string) error {
	query := `UPDATE tweets SET deleted_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// ======================================================================
= Follow Queries
// ======================================================================

// CreateFollow creates a follow relationship.
func (q *Queries) CreateFollow(ctx context.Context, followerID, followeeID string) error {
	query := `INSERT INTO follows (follower_id, followee_id, created_at) VALUES ($1, $2, NOW())`
	_, err := q.db.ExecContext(ctx, query, followerID, followeeID)
	return err
}

// DeleteFollow removes a follow relationship.
func (q *Queries) DeleteFollow(ctx context.Context, followerID, followeeID string) error {
	query := `DELETE FROM follows WHERE follower_id = $1 AND followee_id = $2`
	_, err := q.db.ExecContext(ctx, query, followerID, followeeID)
	return err
}

// FollowExists checks if a follow relationship exists.
func (q *Queries) FollowExists(ctx context.Context, followerID, followeeID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM follows WHERE follower_id = $1 AND followee_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, followerID, followeeID).Scan(&exists)
	return exists, err
}

// CountFollowers counts followers of a user.
func (q *Queries) CountFollowers(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM follows WHERE followee_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// CountFollowing counts users followed by a user.
func (q *Queries) CountFollowing(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM follows WHERE follower_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// ======================================================================
= Like Queries
// ======================================================================

// CreateLike creates a like.
func (q *Queries) CreateLike(ctx context.Context, tweetID, userID string) error {
	query := `INSERT INTO likes (tweet_id, user_id, created_at) VALUES ($1, $2, NOW())`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// DeleteLike removes a like.
func (q *Queries) DeleteLike(ctx context.Context, tweetID, userID string) error {
	query := `DELETE FROM likes WHERE tweet_id = $1 AND user_id = $2`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// LikeExists checks if a like exists.
func (q *Queries) LikeExists(ctx context.Context, tweetID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM likes WHERE tweet_id = $1 AND user_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, tweetID, userID).Scan(&exists)
	return exists, err
}

// CountLikes counts likes for a tweet.
func (q *Queries) CountLikes(ctx context.Context, tweetID string) (int64, error) {
	query := `SELECT COUNT(*) FROM likes WHERE tweet_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, tweetID).Scan(&count)
	return count, err
}

// ======================================================================
= Retweet Queries
// ======================================================================

// CreateRetweet creates a retweet.
func (q *Queries) CreateRetweet(ctx context.Context, tweetID, userID string) error {
	query := `INSERT INTO retweets (tweet_id, user_id, created_at) VALUES ($1, $2, NOW())`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// DeleteRetweet removes a retweet.
func (q *Queries) DeleteRetweet(ctx context.Context, tweetID, userID string) error {
	query := `DELETE FROM retweets WHERE tweet_id = $1 AND user_id = $2`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// RetweetExists checks if a retweet exists.
func (q *Queries) RetweetExists(ctx context.Context, tweetID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM retweets WHERE tweet_id = $1 AND user_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, tweetID, userID).Scan(&exists)
	return exists, err
}

// CountRetweets counts retweets for a tweet.
func (q *Queries) CountRetweets(ctx context.Context, tweetID string) (int64, error) {
	query := `SELECT COUNT(*) FROM retweets WHERE tweet_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, tweetID).Scan(&count)
	return count, err
}

// ======================================================================
= Bookmark Queries
// ======================================================================

// CreateBookmark creates a bookmark.
func (q *Queries) CreateBookmark(ctx context.Context, tweetID, userID string) error {
	query := `INSERT INTO bookmarks (tweet_id, user_id, created_at) VALUES ($1, $2, NOW())`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// DeleteBookmark removes a bookmark.
func (q *Queries) DeleteBookmark(ctx context.Context, tweetID, userID string) error {
	query := `DELETE FROM bookmarks WHERE tweet_id = $1 AND user_id = $2`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// BookmarkExists checks if a bookmark exists.
func (q *Queries) BookmarkExists(ctx context.Context, tweetID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM bookmarks WHERE tweet_id = $1 AND user_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, tweetID, userID).Scan(&exists)
	return exists, err
}

// CountBookmarks counts bookmarks for a tweet.
func (q *Queries) CountBookmarks(ctx context.Context, tweetID string) (int64, error) {
	query := `SELECT COUNT(*) FROM bookmarks WHERE tweet_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, tweetID).Scan(&count)
	return count, err
}

// ======================================================================
= Message Queries
// ======================================================================

// CreateMessage creates a direct message.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	query := `
		INSERT INTO messages (
			id, sender_id, receiver_id, content, media_urls,
			read, read_at, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.SenderID, arg.ReceiverID, arg.Content,
		pq.Array(arg.MediaURLs), arg.Read, arg.ReadAt,
		arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

// GetMessagesBetweenUsers returns messages between two users.
func (q *Queries) GetMessagesBetweenUsers(ctx context.Context, user1ID, user2ID string, limit int32, cursor string) ([]*Message, error) {
	query := `
		SELECT * FROM messages
		WHERE (sender_id = $1 AND receiver_id = $2) OR (sender_id = $2 AND receiver_id = $1)
		AND deleted_at IS NULL
		ORDER BY created_at DESC LIMIT $3
	`
	rows, err := q.db.QueryContext(ctx, query, user1ID, user2ID, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var messages []*Message
	for rows.Next() {
		var m Message
		if err := rows.Scan(
			&m.ID, &m.SenderID, &m.ReceiverID, &m.Content,
			pq.Array(&m.MediaURLs), &m.Read, &m.ReadAt,
			&m.CreatedAt, &m.UpdatedAt, &m.DeletedAt,
		); err != nil {
			return nil, err
		}
		messages = append(messages, &m)
	}
	return messages, rows.Err()
}

// CountUnreadMessages counts unread messages for a user.
func (q *Queries) CountUnreadMessages(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM messages WHERE receiver_id = $1 AND read = false AND deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// MarkMessageRead marks a message as read.
func (q *Queries) MarkMessageRead(ctx context.Context, id string) error {
	query := `UPDATE messages SET read = true, read_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// ======================================================================
= Notification Queries
// ======================================================================

// CreateNotification creates a notification.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	query := `
		INSERT INTO notifications (
			id, user_id, from_user_id, type, reference_id, read, created_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.UserID, arg.FromUserID, arg.Type,
		arg.ReferenceID, arg.Read, arg.CreatedAt,
	)
	return err
}

// GetNotificationsByUserID retrieves notifications for a user.
func (q *Queries) GetNotificationsByUserID(ctx context.Context, userID string, limit int32, offset int32) ([]*Notification, error) {
	query := `
		SELECT * FROM notifications
		WHERE user_id = $1
		ORDER BY created_at DESC LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, userID, limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var notifications []*Notification
	for rows.Next() {
		var n Notification
		if err := rows.Scan(
			&n.ID, &n.UserID, &n.FromUserID, &n.Type,
			&n.ReferenceID, &n.Read, &n.CreatedAt,
		); err != nil {
			return nil, err
		}
		notifications = append(notifications, &n)
	}
	return notifications, rows.Err()
}

// CountUnreadNotifications counts unread notifications for a user.
func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read = false`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// MarkNotificationRead marks a notification as read.
func (q *Queries) MarkNotificationRead(ctx context.Context, id string) error {
	query := `UPDATE notifications SET read = true WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// ======================================================================
= Community Queries
// ======================================================================

// CreateCommunity creates a community.
func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) error {
	query := `
		INSERT INTO communities (
			id, name, slug, description, avatar_url, banner_url,
			created_by, is_private, member_count, post_count, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.Name, arg.Slug, arg.Description, arg.AvatarURL,
		arg.BannerURL, arg.CreatedBy, arg.IsPrivate, arg.MemberCount,
		arg.PostCount, arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

// GetCommunityByID retrieves a community by ID.
func (q *Queries) GetCommunityByID(ctx context.Context, id string) (*Community, error) {
	query := `SELECT * FROM communities WHERE id = $1 AND deleted_at IS NULL`
	var c Community
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&c.ID, &c.Name, &c.Slug, &c.Description, &c.AvatarURL,
		&c.BannerURL, &c.CreatedBy, &c.IsPrivate, &c.MemberCount,
		&c.PostCount, &c.CreatedAt, &c.UpdatedAt, &c.DeletedAt,
	)
	if err != nil {
		return nil, err
	}
	return &c, nil
}

// AddCommunityMember adds a member to a community.
func (q *Queries) AddCommunityMember(ctx context.Context, communityID, userID, role string) error {
	query := `
		INSERT INTO community_members (community_id, user_id, role, joined_at)
		VALUES ($1, $2, $3, NOW())
	`
	_, err := q.db.ExecContext(ctx, query, communityID, userID, role)
	if err != nil {
		return err
	}
	// Increment member count
	_, err = q.db.ExecContext(ctx, `UPDATE communities SET member_count = member_count + 1 WHERE id = $1`, communityID)
	return err
}

// RemoveCommunityMember removes a member from a community.
func (q *Queries) RemoveCommunityMember(ctx context.Context, communityID, userID string) error {
	query := `DELETE FROM community_members WHERE community_id = $1 AND user_id = $2`
	_, err := q.db.ExecContext(ctx, query, communityID, userID)
	if err != nil {
		return err
	}
	// Decrement member count
	_, err = q.db.ExecContext(ctx, `UPDATE communities SET member_count = GREATEST(member_count - 1, 0) WHERE id = $1`, communityID)
	return err
}

// ======================================================================
= Report Queries
// ======================================================================

// CreateReport creates a report.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	query := `
		INSERT INTO reports (
			id, reporter_id, target_id, target_type, reason,
			description, status, severity, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.ReporterID, arg.TargetID, arg.TargetType,
		arg.Reason, arg.Description, arg.Status, arg.Severity,
		arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

// GetReportByID retrieves a report by ID.
func (q *Queries) GetReportByID(ctx context.Context, id string) (*Report, error) {
	query := `SELECT * FROM reports WHERE id = $1`
	var r Report
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&r.ID, &r.ReporterID, &r.TargetID, &r.TargetType,
		&r.Reason, &r.Description, &r.Status, &r.Severity,
		&r.CreatedAt, &r.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

// UpdateReportStatus updates the status of a report.
func (q *Queries) UpdateReportStatus(ctx context.Context, id, status, reviewerID, notes string) error {
	query := `
		UPDATE reports SET status = $1, reviewer_id = $2, review_notes = $3, resolved_at = NOW(), updated_at = NOW()
		WHERE id = $4
	`
	_, err := q.db.ExecContext(ctx, query, status, reviewerID, notes, id)
	return err
}