// backend/sqlc/models.go
// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

// ======================================================================
// User Model
// ======================================================================

// User represents a user in the database.
type User struct {
	ID            string         `db:"id" json:"id"`
	Username      string         `db:"username" json:"username"`
	Email         string         `db:"email" json:"email"`
	PasswordHash  string         `db:"password_hash" json:"-"`
	FullName      string         `db:"full_name" json:"full_name"`
	Bio           string         `db:"bio" json:"bio,omitempty"`
	AvatarURL     string         `db:"avatar_url" json:"avatar_url,omitempty"`
	BannerURL     string         `db:"banner_url" json:"banner_url,omitempty"`
	Location      string         `db:"location" json:"location,omitempty"`
	Website       string         `db:"website" json:"website,omitempty"`
	Role          string         `db:"role" json:"role"`
	Status        string         `db:"status" json:"status"`
	IsVerified    bool           `db:"is_verified" json:"is_verified"`
	IsPrivate     bool           `db:"is_private" json:"is_private"`
	TwitterHandle string         `db:"twitter_handle" json:"twitter_handle,omitempty"`
	InstagramHandle string       `db:"instagram_handle" json:"instagram_handle,omitempty"`
	TweetCount    int64          `db:"tweet_count" json:"tweet_count"`
	FollowerCount int64          `db:"follower_count" json:"follower_count"`
	FollowingCount int64         `db:"following_count" json:"following_count"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at" json:"deleted_at,omitempty"`
	LastActive    sql.NullTime   `db:"last_active" json:"last_active_at,omitempty"`
	Metadata      json.RawMessage `db:"metadata" json:"metadata,omitempty"`
}

// ======================================================================
// Tweet Model
// ======================================================================

// Tweet represents a tweet in the database.
type Tweet struct {
	ID            string         `db:"id" json:"id"`
	UserID        string         `db:"user_id" json:"user_id"`
	Content       string         `db:"content" json:"content"`
	MediaURLs     pq.StringArray `db:"media_urls" json:"media_urls,omitempty"`
	ParentTweetID *string        `db:"parent_tweet_id" json:"parent_tweet_id,omitempty"`
	RetweetOfID   *string        `db:"retweet_of_id" json:"retweet_of_id,omitempty"`
	IsPoll        bool           `db:"is_poll" json:"is_poll"`
	ViewCount     int64          `db:"view_count" json:"view_count"`
	CreatedAt     time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt     time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt     sql.NullTime   `db:"deleted_at" json:"deleted_at,omitempty"`
	Metadata      json.RawMessage `db:"metadata" json:"metadata,omitempty"`
}

// ======================================================================
= Follow Model
// ======================================================================

// Follow represents a follow relationship in the database.
type Follow struct {
	FollowerID string       `db:"follower_id" json:"follower_id"`
	FolloweeID string       `db:"followee_id" json:"followee_id"`
	Status     string       `db:"status" json:"status"`
	CreatedAt  time.Time    `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time    `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime `db:"deleted_at" json:"deleted_at,omitempty"`
}

// ======================================================================
= Like Model
// ======================================================================

// Like represents a like in the database.
type Like struct {
	TweetID   string       `db:"tweet_id" json:"tweet_id"`
	UserID    string       `db:"user_id" json:"user_id"`
	Type      string       `db:"type" json:"type"`
	CreatedAt time.Time    `db:"created_at" json:"created_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at,omitempty"`
}

// ======================================================================
= Retweet Model
// ======================================================================

// Retweet represents a retweet in the database.
type Retweet struct {
	TweetID     string       `db:"tweet_id" json:"tweet_id"`
	UserID      string       `db:"user_id" json:"user_id"`
	Type        string       `db:"type" json:"type"`
	QuoteContent string      `db:"quote_content" json:"quote_content,omitempty"`
	CreatedAt   time.Time    `db:"created_at" json:"created_at"`
	DeletedAt   sql.NullTime `db:"deleted_at" json:"deleted_at,omitempty"`
}

// ======================================================================
= Bookmark Model
// ======================================================================

// Bookmark represents a bookmark in the database.
type Bookmark struct {
	TweetID   string         `db:"tweet_id" json:"tweet_id"`
	UserID    string         `db:"user_id" json:"user_id"`
	Category  string         `db:"category" json:"category"`
	Name      string         `db:"name" json:"name,omitempty"`
	Notes     string         `db:"notes" json:"notes,omitempty"`
	Metadata  json.RawMessage `db:"metadata" json:"metadata,omitempty"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at" json:"deleted_at,omitempty"`
}

// ======================================================================
= Poll Model
// ======================================================================

// Poll represents a poll in the database.
type Poll struct {
	ID        string         `db:"id" json:"id"`
	TweetID   string         `db:"tweet_id" json:"tweet_id"`
	Question  string         `db:"question" json:"question"`
	Options   json.RawMessage `db:"options" json:"options"`
	Duration  int64          `db:"duration" json:"duration"`
	ExpiresAt time.Time      `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime   `db:"deleted_at" json:"deleted_at,omitempty"`
}

// ======================================================================
= Message Model
// ======================================================================

// Message represents a direct message in the database.
type Message struct {
	ID         string         `db:"id" json:"id"`
	SenderID   string         `db:"sender_id" json:"sender_id"`
	ReceiverID string         `db:"receiver_id" json:"receiver_id"`
	Content    string         `db:"content" json:"content"`
	MediaURLs  pq.StringArray `db:"media_urls" json:"media_urls,omitempty"`
	Read       bool           `db:"read" json:"read"`
	ReadAt     sql.NullTime   `db:"read_at" json:"read_at,omitempty"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt  time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt  sql.NullTime   `db:"deleted_at" json:"deleted_at,omitempty"`
	Metadata   json.RawMessage `db:"metadata" json:"metadata,omitempty"`
}

// ======================================================================
= Notification Model
// ======================================================================

// Notification represents a notification in the database.
type Notification struct {
	ID          string         `db:"id" json:"id"`
	UserID      string         `db:"user_id" json:"user_id"`
	FromUserID  string         `db:"from_user_id" json:"from_user_id"`
	Type        string         `db:"type" json:"type"`
	ReferenceID string         `db:"reference_id" json:"reference_id,omitempty"`
	Read        bool           `db:"read" json:"read"`
	ReadAt      sql.NullTime   `db:"read_at" json:"read_at,omitempty"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	Metadata    json.RawMessage `db:"metadata" json:"metadata,omitempty"`
}

// ======================================================================
= Session Model
// ======================================================================

// Session represents a user session in the database.
type Session struct {
	ID           string         `db:"id" json:"id"`
	UserID       string         `db:"user_id" json:"user_id"`
	RefreshToken string         `db:"refresh_token" json:"refresh_token"`
	Status       string         `db:"status" json:"status"`
	Type         string         `db:"type" json:"type"`
	UserAgent    string         `db:"user_agent" json:"user_agent,omitempty"`
	IP           string         `db:"ip" json:"ip,omitempty"`
	DeviceID     string         `db:"device_id" json:"device_id,omitempty"`
	DeviceName   string         `db:"device_name" json:"device_name,omitempty"`
	OS           string         `db:"os" json:"os,omitempty"`
	Browser      string         `db:"browser" json:"browser,omitempty"`
	Location     string         `db:"location" json:"location,omitempty"`
	ExpiresAt    time.Time      `db:"expires_at" json:"expires_at"`
	LastActive   sql.NullTime   `db:"last_active" json:"last_active_at,omitempty"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullTime   `db:"deleted_at" json:"deleted_at,omitempty"`
	Metadata     json.RawMessage `db:"metadata" json:"metadata,omitempty"`
}

// ======================================================================
= Community Model
// ======================================================================

// Community represents a community in the database.
type Community struct {
	ID          string         `db:"id" json:"id"`
	Name        string         `db:"name" json:"name"`
	Slug        string         `db:"slug" json:"slug"`
	Description string         `db:"description" json:"description,omitempty"`
	AvatarURL   string         `db:"avatar_url" json:"avatar_url,omitempty"`
	BannerURL   string         `db:"banner_url" json:"banner_url,omitempty"`
	CreatedBy   string         `db:"created_by" json:"created_by"`
	IsPrivate   bool           `db:"is_private" json:"is_private"`
	Status      string         `db:"status" json:"status"`
	MemberCount int64          `db:"member_count" json:"member_count"`
	PostCount   int64          `db:"post_count" json:"post_count"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at,omitempty"`
	Settings    json.RawMessage `db:"settings" json:"settings,omitempty"`
	Tags        pq.StringArray `db:"tags" json:"tags,omitempty"`
}

// ======================================================================
= CommunityMember Model
// ======================================================================

// CommunityMember represents a community member in the database.
type CommunityMember struct {
	CommunityID string       `db:"community_id" json:"community_id"`
	UserID      string       `db:"user_id" json:"user_id"`
	Role        string       `db:"role" json:"role"`
	JoinedAt    time.Time    `db:"joined_at" json:"joined_at"`
	UpdatedAt   time.Time    `db:"updated_at" json:"updated_at"`
}

// ======================================================================
= CommunityPost Model
// ======================================================================

// CommunityPost represents a post in a community.
type CommunityPost struct {
	CommunityID string    `db:"community_id" json:"community_id"`
	TweetID     string    `db:"tweet_id" json:"tweet_id"`
	CreatedAt   time.Time `db:"created_at" json:"created_at"`
}

// ======================================================================
= Report Model
// ======================================================================

// Report represents a report in the database.
type Report struct {
	ID          string         `db:"id" json:"id"`
	ReporterID  string         `db:"reporter_id" json:"reporter_id"`
	TargetID    string         `db:"target_id" json:"target_id"`
	TargetType  string         `db:"target_type" json:"target_type"`
	Type        string         `db:"type" json:"type"`
	Reason      string         `db:"reason" json:"reason"`
	Description string         `db:"description" json:"description,omitempty"`
	Status      string         `db:"status" json:"status"`
	Severity    string         `db:"severity" json:"severity"`
	ReviewerID  string         `db:"reviewer_id" json:"reviewer_id,omitempty"`
	ReviewNotes string         `db:"review_notes" json:"review_notes,omitempty"`
	ResolvedAt  sql.NullTime   `db:"resolved_at" json:"resolved_at,omitempty"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt   time.Time      `db:"updated_at" json:"updated_at"`
	Metadata    json.RawMessage `db:"metadata" json:"metadata,omitempty"`
}

// ======================================================================
= CommunityBan Model
// ======================================================================

// CommunityBan represents a banned user in a community.
type CommunityBan struct {
	CommunityID string       `db:"community_id" json:"community_id"`
	UserID      string       `db:"user_id" json:"user_id"`
	Reason      string       `db:"reason" json:"reason,omitempty"`
	BannedBy    string       `db:"banned_by" json:"banned_by"`
	BannedAt    time.Time    `db:"banned_at" json:"banned_at"`
	ExpiresAt   sql.NullTime `db:"expires_at" json:"expires_at,omitempty"`
}

// ======================================================================
= AuditLog Model
// ======================================================================

// AuditLog represents an audit log entry.
type AuditLog struct {
	ID         string         `db:"id" json:"id"`
	UserID     string         `db:"user_id" json:"user_id,omitempty"`
	Action     string         `db:"action" json:"action"`
	Resource   string         `db:"resource" json:"resource"`
	ResourceID string         `db:"resource_id" json:"resource_id,omitempty"`
	IP         string         `db:"ip" json:"ip,omitempty"`
	UserAgent  string         `db:"user_agent" json:"user_agent,omitempty"`
	Status     string         `db:"status" json:"status"`
	Details    json.RawMessage `db:"details" json:"details,omitempty"`
	CreatedAt  time.Time      `db:"created_at" json:"created_at"`
}

// ======================================================================
= TrendingTopic Model
// ======================================================================

// TrendingTopic represents a trending topic.
type TrendingTopic struct {
	Hashtag   string    `db:"hashtag" json:"hashtag"`
	Count     int64     `db:"count" json:"count"`
	FirstSeen time.Time `db:"first_seen" json:"first_seen"`
	LastSeen  time.Time `db:"last_seen" json:"last_seen"`
}

// ======================================================================
= SearchIndex Model
// ======================================================================

// SearchIndex represents a search index entry.
type SearchIndex struct {
	ID          string         `db:"id" json:"id"`
	Type        string         `db:"type" json:"type"` // "tweet", "user", "hashtag"
	Content     string         `db:"content" json:"content"`
	UserID      string         `db:"user_id" json:"user_id,omitempty"`
	CreatedAt   time.Time      `db:"created_at" json:"created_at"`
	Metadata    json.RawMessage `db:"metadata" json:"metadata,omitempty"`
}

// ======================================================================
= DailyStat Model
// ======================================================================

// DailyStat represents daily statistics.
type DailyStat struct {
	Date         time.Time `db:"date" json:"date"`
	NewUsers     int64     `db:"new_users" json:"new_users"`
	ActiveUsers  int64     `db:"active_users" json:"active_users"`
	NewTweets    int64     `db:"new_tweets" json:"new_tweets"`
	NewLikes     int64     `db:"new_likes" json:"new_likes"`
	NewRetweets  int64     `db:"new_retweets" json:"new_retweets"`
	NewFollows   int64     `db:"new_follows" json:"new_follows"`
	NewMessages  int64     `db:"new_messages" json:"new_messages"`
	TotalUsers   int64     `db:"total_users" json:"total_users"`
	TotalTweets  int64     `db:"total_tweets" json:"total_tweets"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

// ======================================================================
= NotificationSettings Model
// ======================================================================

// NotificationSettings represents user notification preferences.
type NotificationSettings struct {
	UserID       string    `db:"user_id" json:"user_id"`
	Likes        bool      `db:"likes" json:"likes"`
	Retweets     bool      `db:"retweets" json:"retweets"`
	Follows      bool      `db:"follows" json:"follows"`
	Replies      bool      `db:"replies" json:"replies"`
	Mentions     bool      `db:"mentions" json:"mentions"`
	Quotes       bool      `db:"quotes" json:"quotes"`
	Messages     bool      `db:"messages" json:"messages"`
	Community    bool      `db:"community" json:"community"`
	Email        bool      `db:"email" json:"email"`
	Push         bool      `db:"push" json:"push"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}

// ======================================================================
= UserSettings Model
// ======================================================================

// UserSettings represents user preferences.
type UserSettings struct {
	UserID     string         `db:"user_id" json:"user_id"`
	Theme      string         `db:"theme" json:"theme"`
	Language   string         `db:"language" json:"language"`
	Timezone   string         `db:"timezone" json:"timezone"`
	Privacy    json.RawMessage `db:"privacy" json:"privacy,omitempty"`
	UpdatedAt  time.Time      `db:"updated_at" json:"updated_at"`
}

// ======================================================================
= Space Model (Audio Rooms)
// ======================================================================

// Space represents an audio room/space.
type Space struct {
	ID           string         `db:"id" json:"id"`
	Title        string         `db:"title" json:"title"`
	Description  string         `db:"description" json:"description,omitempty"`
	Topic        string         `db:"topic" json:"topic,omitempty"`
	CreatedBy    string         `db:"created_by" json:"created_by"`
	Visibility   string         `db:"visibility" json:"visibility"`
	Type         string         `db:"type" json:"type"`
	Status       string         `db:"status" json:"status"`
	ScheduledAt  sql.NullTime   `db:"scheduled_at" json:"scheduled_at,omitempty"`
	StartedAt    sql.NullTime   `db:"started_at" json:"started_at,omitempty"`
	EndedAt      sql.NullTime   `db:"ended_at" json:"ended_at,omitempty"`
	Duration     int64          `db:"duration" json:"duration"`
	SpeakerCount int64          `db:"speaker_count" json:"speaker_count"`
	ListenerCount int64         `db:"listener_count" json:"listener_count"`
	MaxListeners int64          `db:"max_listeners" json:"max_listeners"`
	InviteCode   string         `db:"invite_code" json:"invite_code,omitempty"`
	CreatedAt    time.Time      `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
	DeletedAt    sql.NullTime   `db:"deleted_at" json:"deleted_at,omitempty"`
	Metadata     json.RawMessage `db:"metadata" json:"metadata,omitempty"`
}

// ======================================================================
= SpaceParticipant Model
// ======================================================================

// SpaceParticipant represents a participant in a space.
type SpaceParticipant struct {
	SpaceID   string       `db:"space_id" json:"space_id"`
	UserID    string       `db:"user_id" json:"user_id"`
	Role      string       `db:"role" json:"role"` // "speaker", "listener"
	Status    string       `db:"status" json:"status"`
	JoinedAt  time.Time    `db:"joined_at" json:"joined_at"`
	LeftAt    sql.NullTime `db:"left_at" json:"left_at,omitempty"`
	Muted     bool         `db:"muted" json:"muted"`
	IsHost    bool         `db:"is_host" json:"is_host"`
}

// ======================================================================
= FeedPreferences Model
// ======================================================================

// FeedPreferences represents user feed preferences.
type FeedPreferences struct {
	UserID       string         `db:"user_id" json:"user_id"`
	Interests    pq.StringArray `db:"interests" json:"interests,omitempty"`
	ShowReplies  bool           `db:"show_replies" json:"show_replies"`
	ShowRetweets bool           `db:"show_retweets" json:"show_retweets"`
	FeedType     string         `db:"feed_type" json:"feed_type"`
	UpdatedAt    time.Time      `db:"updated_at" json:"updated_at"`
}

// ======================================================================
= DismissedFeedItem Model
// ======================================================================

// DismissedFeedItem represents a dismissed feed item.
type DismissedFeedItem struct {
	UserID    string    `db:"user_id" json:"user_id"`
	TweetID   string    `db:"tweet_id" json:"tweet_id"`
	DismissedAt time.Time `db:"dismissed_at" json:"dismissed_at"`
}

// ======================================================================
= Block Model
// ======================================================================

// Block represents a blocked user relationship.
type Block struct {
	BlockerID string    `db:"blocker_id" json:"blocker_id"`
	BlockedID string    `db:"blocked_id" json:"blocked_id"`
	Reason    string    `db:"reason" json:"reason,omitempty"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

// ======================================================================
= Mute Model
// ======================================================================

// Mute represents a muted user relationship.
type Mute struct {
	MuterID   string    `db:"muter_id" json:"muter_id"`
	MutedID   string    `db:"muted_id" json:"muted_id"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
	ExpiresAt sql.NullTime `db:"expires_at" json:"expires_at,omitempty"`
}