// backend/sqlc/query.sql.go
// Code generated by sqlc. DO NOT EDIT.
package sqlc

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/lib/pq"
)

// ======================================================================
// User Queries
// ======================================================================

// CreateUserParams are the parameters for creating a user.
type CreateUserParams struct {
	ID            string
	Username      string
	Email         string
	PasswordHash  string
	FullName      string
	Bio           string
	AvatarURL     string
	BannerURL     string
	Location      string
	Website       string
	Role          string
	Status        string
	IsVerified    bool
	IsPrivate     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// CreateUser creates a new user.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	query := `
		INSERT INTO users (
			id, username, email, password_hash, full_name, bio,
			avatar_url, banner_url, location, website, role, status,
			is_verified, is_private, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.Username, arg.Email, arg.PasswordHash, arg.FullName, arg.Bio,
		arg.AvatarURL, arg.BannerURL, arg.Location, arg.Website,
		arg.Role, arg.Status, arg.IsVerified, arg.IsPrivate,
		arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

// GetUserByIDRow represents a user row.
type GetUserByIDRow struct {
	ID            string
	Username      string
	Email         string
	PasswordHash  string
	FullName      string
	Bio           string
	AvatarURL     string
	BannerURL     string
	Location      string
	Website       string
	Role          string
	Status        string
	IsVerified    bool
	IsPrivate     bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
	LastActive    sql.NullTime
	Metadata      json.RawMessage
}

// GetUserByID retrieves a user by ID.
func (q *Queries) GetUserByID(ctx context.Context, id string) (*GetUserByIDRow, error) {
	query := `SELECT * FROM users WHERE id = $1 AND deleted_at IS NULL`
	var row GetUserByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.Username, &row.Email, &row.PasswordHash, &row.FullName,
		&row.Bio, &row.AvatarURL, &row.BannerURL, &row.Location, &row.Website,
		&row.Role, &row.Status, &row.IsVerified, &row.IsPrivate,
		&row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.LastActive, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetUserByUsername retrieves a user by username.
func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*GetUserByIDRow, error) {
	query := `SELECT * FROM users WHERE username = $1 AND deleted_at IS NULL`
	var row GetUserByIDRow
	err := q.db.QueryRowContext(ctx, query, username).Scan(
		&row.ID, &row.Username, &row.Email, &row.PasswordHash, &row.FullName,
		&row.Bio, &row.AvatarURL, &row.BannerURL, &row.Location, &row.Website,
		&row.Role, &row.Status, &row.IsVerified, &row.IsPrivate,
		&row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.LastActive, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetUserByEmail retrieves a user by email.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*GetUserByIDRow, error) {
	query := `SELECT * FROM users WHERE email = $1 AND deleted_at IS NULL`
	var row GetUserByIDRow
	err := q.db.QueryRowContext(ctx, query, email).Scan(
		&row.ID, &row.Username, &row.Email, &row.PasswordHash, &row.FullName,
		&row.Bio, &row.AvatarURL, &row.BannerURL, &row.Location, &row.Website,
		&row.Role, &row.Status, &row.IsVerified, &row.IsPrivate,
		&row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.LastActive, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetUserByUsernameOrEmail retrieves a user by either username or email.
func (q *Queries) GetUserByUsernameOrEmail(ctx context.Context, identifier string) (*GetUserByIDRow, error) {
	query := `SELECT * FROM users WHERE (username = $1 OR email = $2) AND deleted_at IS NULL`
	var row GetUserByIDRow
	err := q.db.QueryRowContext(ctx, query, identifier, identifier).Scan(
		&row.ID, &row.Username, &row.Email, &row.PasswordHash, &row.FullName,
		&row.Bio, &row.AvatarURL, &row.BannerURL, &row.Location, &row.Website,
		&row.Role, &row.Status, &row.IsVerified, &row.IsPrivate,
		&row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.LastActive, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// ListUsersParams are the parameters for listing users.
type ListUsersParams struct {
	Limit  int32
	Offset int32
	SortBy string
	Order  string
}

// ListUsers returns a paginated list of users.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]*GetUserByIDRow, error) {
	query := fmt.Sprintf(`SELECT * FROM users WHERE deleted_at IS NULL ORDER BY %s %s LIMIT $1 OFFSET $2`, arg.SortBy, arg.Order)
	rows, err := q.db.QueryContext(ctx, query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var users []*GetUserByIDRow
	for rows.Next() {
		var row GetUserByIDRow
		if err := rows.Scan(
			&row.ID, &row.Username, &row.Email, &row.PasswordHash, &row.FullName,
			&row.Bio, &row.AvatarURL, &row.BannerURL, &row.Location, &row.Website,
			&row.Role, &row.Status, &row.IsVerified, &row.IsPrivate,
			&row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.LastActive, &row.Metadata,
		); err != nil {
			return nil, err
		}
		users = append(users, &row)
	}
	return users, rows.Err()
}

// CountUsers returns the total number of users.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	query := `SELECT COUNT(*) FROM users WHERE deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query).Scan(&count)
	return count, err
}

// UpdateUser updates a user.
func (q *Queries) UpdateUser(ctx context.Context, arg User) error {
	query := `
		UPDATE users SET
			username = $1, email = $2, password_hash = $3, full_name = $4,
			bio = $5, avatar_url = $6, banner_url = $7, location = $8,
			website = $9, role = $10, status = $11, is_verified = $12,
			is_private = $13, updated_at = $14
		WHERE id = $15 AND deleted_at IS NULL
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.Username, arg.Email, arg.PasswordHash, arg.FullName,
		arg.Bio, arg.AvatarURL, arg.BannerURL, arg.Location,
		arg.Website, arg.Role, arg.Status, arg.IsVerified,
		arg.IsPrivate, arg.UpdatedAt, arg.ID,
	)
	return err
}

// SoftDeleteUser soft deletes a user.
func (q *Queries) SoftDeleteUser(ctx context.Context, id string) error {
	query := `UPDATE users SET deleted_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// HardDeleteUser permanently deletes a user.
func (q *Queries) HardDeleteUser(ctx context.Context, id string) error {
	query := `DELETE FROM users WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// IncrementUserTweetCount increments the tweet count for a user.
func (q *Queries) IncrementUserTweetCount(ctx context.Context, id string) error {
	query := `UPDATE users SET tweet_count = tweet_count + 1 WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// DecrementUserTweetCount decrements the tweet count for a user.
func (q *Queries) DecrementUserTweetCount(ctx context.Context, id string) error {
	query := `UPDATE users SET tweet_count = GREATEST(tweet_count - 1, 0) WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// IncrementUserFollowerCount increments the follower count.
func (q *Queries) IncrementUserFollowerCount(ctx context.Context, id string) error {
	query := `UPDATE users SET follower_count = follower_count + 1 WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// DecrementUserFollowerCount decrements the follower count.
func (q *Queries) DecrementUserFollowerCount(ctx context.Context, id string) error {
	query := `UPDATE users SET follower_count = GREATEST(follower_count - 1, 0) WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// IncrementUserFollowingCount increments the following count.
func (q *Queries) IncrementUserFollowingCount(ctx context.Context, id string) error {
	query := `UPDATE users SET following_count = following_count + 1 WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// DecrementUserFollowingCount decrements the following count.
func (q *Queries) DecrementUserFollowingCount(ctx context.Context, id string) error {
	query := `UPDATE users SET following_count = GREATEST(following_count - 1, 0) WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// UpdateUserLastActive updates the last active timestamp.
func (q *Queries) UpdateUserLastActive(ctx context.Context, id string) error {
	query := `UPDATE users SET last_active = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// SearchUsersParams are the parameters for searching users.
type SearchUsersParams struct {
	Query  string
	Limit  int32
	Offset int32
}

// SearchUsers searches for users by username, full name, or bio.
func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]*GetUserByIDRow, error) {
	query := `
		SELECT * FROM users 
		WHERE deleted_at IS NULL 
		  AND (username ILIKE '%' || $1 || '%' 
		    OR full_name ILIKE '%' || $1 || '%' 
		    OR bio ILIKE '%' || $1 || '%')
		ORDER BY 
			CASE 
				WHEN username ILIKE $1 THEN 1
				WHEN full_name ILIKE $1 THEN 2
				ELSE 3
			END,
			username
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var users []*GetUserByIDRow
	for rows.Next() {
		var row GetUserByIDRow
		if err := rows.Scan(
			&row.ID, &row.Username, &row.Email, &row.PasswordHash, &row.FullName,
			&row.Bio, &row.AvatarURL, &row.BannerURL, &row.Location, &row.Website,
			&row.Role, &row.Status, &row.IsVerified, &row.IsPrivate,
			&row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.LastActive, &row.Metadata,
		); err != nil {
			return nil, err
		}
		users = append(users, &row)
	}
	return users, rows.Err()
}

// GetUsersByIDsParams are the parameters for getting users by IDs.
type GetUsersByIDsParams struct {
	IDs []string
}

// GetUsersByIDs retrieves multiple users by their IDs.
func (q *Queries) GetUsersByIDs(ctx context.Context, arg GetUsersByIDsParams) ([]*GetUserByIDRow, error) {
	query := `SELECT * FROM users WHERE id = ANY($1::text[]) AND deleted_at IS NULL`
	rows, err := q.db.QueryContext(ctx, query, pq.Array(arg.IDs))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var users []*GetUserByIDRow
	for rows.Next() {
		var row GetUserByIDRow
		if err := rows.Scan(
			&row.ID, &row.Username, &row.Email, &row.PasswordHash, &row.FullName,
			&row.Bio, &row.AvatarURL, &row.BannerURL, &row.Location, &row.Website,
			&row.Role, &row.Status, &row.IsVerified, &row.IsPrivate,
			&row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.LastActive, &row.Metadata,
		); err != nil {
			return nil, err
		}
		users = append(users, &row)
	}
	return users, rows.Err()
}

// GetUserStatsRow represents a user stats row.
type GetUserStatsRow struct {
	UserID         string
	TweetCount     int64
	FollowerCount  int64
	FollowingCount int64
	TotalLikes     int64
	TotalRetweets  int64
	TotalReplies   int64
	TotalBookmarks int64
	JoinedAt       time.Time
	LastActive     sql.NullTime
}

// GetUserStats retrieves statistics for a user.
func (q *Queries) GetUserStats(ctx context.Context, userID string) (*GetUserStatsRow, error) {
	query := `
		SELECT 
			u.id AS user_id,
			u.tweet_count,
			u.follower_count,
			u.following_count,
			COUNT(DISTINCT l.id) AS total_likes,
			COUNT(DISTINCT rt.id) AS total_retweets,
			COUNT(DISTINCT r.id) AS total_replies,
			COUNT(DISTINCT b.id) AS total_bookmarks,
			u.created_at AS joined_at,
			u.last_active
		FROM users u
		LEFT JOIN tweets t ON t.user_id = u.id AND t.deleted_at IS NULL
		LEFT JOIN likes l ON l.tweet_id = t.id
		LEFT JOIN retweets rt ON rt.tweet_id = t.id
		LEFT JOIN tweets r ON r.parent_tweet_id = t.id AND r.deleted_at IS NULL
		LEFT JOIN bookmarks b ON b.tweet_id = t.id
		WHERE u.id = $1 AND u.deleted_at IS NULL
		GROUP BY u.id
	`
	var row GetUserStatsRow
	err := q.db.QueryRowContext(ctx, query, userID).Scan(
		&row.UserID, &row.TweetCount, &row.FollowerCount, &row.FollowingCount,
		&row.TotalLikes, &row.TotalRetweets, &row.TotalReplies, &row.TotalBookmarks,
		&row.JoinedAt, &row.LastActive,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// ======================================================================
// Tweet Queries
// ======================================================================

// CreateTweetParams are the parameters for creating a tweet.
type CreateTweetParams struct {
	ID            string
	UserID        string
	Content       string
	MediaURLs     []string
	ParentTweetID *string
	RetweetOfID   *string
	IsPoll        bool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

// CreateTweet inserts a new tweet.
func (q *Queries) CreateTweet(ctx context.Context, arg CreateTweetParams) error {
	query := `
		INSERT INTO tweets (
			id, user_id, content, media_urls, parent_tweet_id,
			retweet_of_id, is_poll, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.UserID, arg.Content, pq.Array(arg.MediaURLs),
		arg.ParentTweetID, arg.RetweetOfID, arg.IsPoll,
		arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

// GetTweetByIDRow represents a tweet row.
type GetTweetByIDRow struct {
	ID            string
	UserID        string
	Content       string
	MediaURLs     []string
	ParentTweetID *string
	RetweetOfID   *string
	IsPoll        bool
	ViewCount     int64
	CreatedAt     time.Time
	UpdatedAt     time.Time
	DeletedAt     sql.NullTime
	Metadata      json.RawMessage
}

// GetTweetByID retrieves a tweet by ID.
func (q *Queries) GetTweetByID(ctx context.Context, id string) (*GetTweetByIDRow, error) {
	query := `SELECT * FROM tweets WHERE id = $1 AND deleted_at IS NULL`
	var row GetTweetByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.UserID, &row.Content, pq.Array(&row.MediaURLs),
		&row.ParentTweetID, &row.RetweetOfID, &row.IsPoll,
		&row.ViewCount, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetTweetsByIDsParams are the parameters for getting tweets by IDs.
type GetTweetsByIDsParams struct {
	IDs []string
}

// GetTweetsByIDs retrieves multiple tweets by their IDs.
func (q *Queries) GetTweetsByIDs(ctx context.Context, arg GetTweetsByIDsParams) ([]*GetTweetByIDRow, error) {
	query := `SELECT * FROM tweets WHERE id = ANY($1::text[]) AND deleted_at IS NULL`
	rows, err := q.db.QueryContext(ctx, query, pq.Array(arg.IDs))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*GetTweetByIDRow
	for rows.Next() {
		var row GetTweetByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.Content, pq.Array(&row.MediaURLs),
			&row.ParentTweetID, &row.RetweetOfID, &row.IsPoll,
			&row.ViewCount, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &row)
	}
	return tweets, rows.Err()
}

// UpdateTweet updates a tweet.
func (q *Queries) UpdateTweet(ctx context.Context, arg GetTweetByIDRow) error {
	query := `
		UPDATE tweets SET
			content = $1,
			media_urls = $2,
			updated_at = $3
		WHERE id = $4 AND deleted_at IS NULL
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.Content, pq.Array(arg.MediaURLs), arg.UpdatedAt, arg.ID,
	)
	return err
}

// SoftDeleteTweet soft deletes a tweet.
func (q *Queries) SoftDeleteTweet(ctx context.Context, id string) error {
	query := `UPDATE tweets SET deleted_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// HardDeleteTweet permanently deletes a tweet.
func (q *Queries) HardDeleteTweet(ctx context.Context, id string) error {
	query := `DELETE FROM tweets WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// RestoreTweet restores a soft-deleted tweet.
func (q *Queries) RestoreTweet(ctx context.Context, id string) error {
	query := `UPDATE tweets SET deleted_at = NULL WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// GetTweetsByUserIDParams are the parameters for getting tweets by user ID.
type GetTweetsByUserIDParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetTweetsByUserID retrieves tweets by a user.
func (q *Queries) GetTweetsByUserID(ctx context.Context, arg GetTweetsByUserIDParams) ([]*GetTweetByIDRow, error) {
	query := `SELECT * FROM tweets WHERE user_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*GetTweetByIDRow
	for rows.Next() {
		var row GetTweetByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.Content, pq.Array(&row.MediaURLs),
			&row.ParentTweetID, &row.RetweetOfID, &row.IsPoll,
			&row.ViewCount, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &row)
	}
	return tweets, rows.Err()
}

// CountTweetsByUserID counts tweets by a user.
func (q *Queries) CountTweetsByUserID(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM tweets WHERE user_id = $1 AND deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// GetFeedTweetsParams are the parameters for getting feed tweets.
type GetFeedTweetsParams struct {
	UserIDs []string
	Limit   int32
}

// GetFeedTweets retrieves tweets for a user's feed.
func (q *Queries) GetFeedTweets(ctx context.Context, arg GetFeedTweetsParams) ([]*GetTweetByIDRow, error) {
	query := `
		SELECT t.* FROM tweets t
		WHERE t.user_id = ANY($1::text[]) 
		  AND t.deleted_at IS NULL
		  AND t.parent_tweet_id IS NULL
		ORDER BY t.created_at DESC
		LIMIT $2
	`
	rows, err := q.db.QueryContext(ctx, query, pq.Array(arg.UserIDs), arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*GetTweetByIDRow
	for rows.Next() {
		var row GetTweetByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.Content, pq.Array(&row.MediaURLs),
			&row.ParentTweetID, &row.RetweetOfID, &row.IsPoll,
			&row.ViewCount, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &row)
	}
	return tweets, rows.Err()
}

// GetFeedTweetsWithCursorParams are the parameters for getting feed tweets with cursor.
type GetFeedTweetsWithCursorParams struct {
	UserIDs []string
	Cursor  time.Time
	Limit   int32
}

// GetFeedTweetsWithCursor retrieves feed tweets with cursor pagination.
func (q *Queries) GetFeedTweetsWithCursor(ctx context.Context, arg GetFeedTweetsWithCursorParams) ([]*GetTweetByIDRow, error) {
	query := `
		SELECT t.* FROM tweets t
		WHERE t.user_id = ANY($1::text[]) 
		  AND t.deleted_at IS NULL
		  AND t.parent_tweet_id IS NULL
		  AND t.created_at < $2
		ORDER BY t.created_at DESC
		LIMIT $3
	`
	rows, err := q.db.QueryContext(ctx, query, pq.Array(arg.UserIDs), arg.Cursor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*GetTweetByIDRow
	for rows.Next() {
		var row GetTweetByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.Content, pq.Array(&row.MediaURLs),
			&row.ParentTweetID, &row.RetweetOfID, &row.IsPoll,
			&row.ViewCount, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &row)
	}
	return tweets, rows.Err()
}

// GetRepliesParams are the parameters for getting replies.
type GetRepliesParams struct {
	ParentTweetID string
	Limit         int32
	Offset        int32
}

// GetReplies retrieves replies to a tweet.
func (q *Queries) GetReplies(ctx context.Context, arg GetRepliesParams) ([]*GetTweetByIDRow, error) {
	query := `SELECT * FROM tweets WHERE parent_tweet_id = $1 AND deleted_at IS NULL ORDER BY created_at ASC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.ParentTweetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*GetTweetByIDRow
	for rows.Next() {
		var row GetTweetByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.Content, pq.Array(&row.MediaURLs),
			&row.ParentTweetID, &row.RetweetOfID, &row.IsPoll,
			&row.ViewCount, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &row)
	}
	return tweets, rows.Err()
}

// CountReplies counts replies to a tweet.
func (q *Queries) CountReplies(ctx context.Context, parentTweetID string) (int64, error) {
	query := `SELECT COUNT(*) FROM tweets WHERE parent_tweet_id = $1 AND deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query, parentTweetID).Scan(&count)
	return count, err
}

// GetRetweetsOfTweetParams are the parameters for getting retweets of a tweet.
type GetRetweetsOfTweetParams struct {
	TweetID string
	Limit   int32
	Offset  int32
}

// GetRetweetsOfTweet retrieves retweets of a tweet.
func (q *Queries) GetRetweetsOfTweet(ctx context.Context, arg GetRetweetsOfTweetParams) ([]*GetTweetByIDRow, error) {
	query := `SELECT * FROM tweets WHERE retweet_of_id = $1 AND deleted_at IS NULL ORDER BY created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.TweetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*GetTweetByIDRow
	for rows.Next() {
		var row GetTweetByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.Content, pq.Array(&row.MediaURLs),
			&row.ParentTweetID, &row.RetweetOfID, &row.IsPoll,
			&row.ViewCount, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &row)
	}
	return tweets, rows.Err()
}

// CountRetweetsOfTweet counts retweets of a tweet.
func (q *Queries) CountRetweetsOfTweet(ctx context.Context, tweetID string) (int64, error) {
	query := `SELECT COUNT(*) FROM tweets WHERE retweet_of_id = $1 AND deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query, tweetID).Scan(&count)
	return count, err
}

// SearchTweetsParams are the parameters for searching tweets.
type SearchTweetsParams struct {
	Query  string
	Limit  int32
	Offset int32
}

// SearchTweetsRow represents a search tweet row with rank.
type SearchTweetsRow struct {
	Tweet GetTweetByIDRow
	Rank  float64
}

// SearchTweets searches for tweets by content.
func (q *Queries) SearchTweets(ctx context.Context, arg SearchTweetsParams) ([]*SearchTweetsRow, error) {
	query := `
		SELECT t.*, 
		       ts_rank(to_tsvector('english', t.content), plainto_tsquery('english', $1)) AS rank
		FROM tweets t
		WHERE to_tsvector('english', t.content) @@ plainto_tsquery('english', $1)
		  AND t.deleted_at IS NULL
		ORDER BY rank DESC, t.created_at DESC
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*SearchTweetsRow
	for rows.Next() {
		var row SearchTweetsRow
		if err := rows.Scan(
			&row.Tweet.ID, &row.Tweet.UserID, &row.Tweet.Content, pq.Array(&row.Tweet.MediaURLs),
			&row.Tweet.ParentTweetID, &row.Tweet.RetweetOfID, &row.Tweet.IsPoll,
			&row.Tweet.ViewCount, &row.Tweet.CreatedAt, &row.Tweet.UpdatedAt, &row.Tweet.DeletedAt, &row.Tweet.Metadata,
			&row.Rank,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// GetTrendingHashtagsRow represents a trending hashtag row.
type GetTrendingHashtagsRow struct {
	Hashtag   string
	Count     int64
	FirstSeen time.Time
	LastSeen  time.Time
}

// GetTrendingHashtags retrieves trending hashtags.
func (q *Queries) GetTrendingHashtags(ctx context.Context, limit int32) ([]*GetTrendingHashtagsRow, error) {
	query := `
		SELECT 
			LOWER(SUBSTRING(t.content FROM '#([A-Za-z0-9_]+)')) AS hashtag,
			COUNT(*) AS count,
			MIN(t.created_at) AS first_seen,
			MAX(t.created_at) AS last_seen
		FROM tweets t
		WHERE t.content ~ '#[A-Za-z0-9_]+'
		  AND t.created_at > NOW() - INTERVAL '24 hours'
		  AND t.deleted_at IS NULL
		GROUP BY hashtag
		ORDER BY count DESC
		LIMIT $1
	`
	rows, err := q.db.QueryContext(ctx, query, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetTrendingHashtagsRow
	for rows.Next() {
		var row GetTrendingHashtagsRow
		if err := rows.Scan(&row.Hashtag, &row.Count, &row.FirstSeen, &row.LastSeen); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// GetMostLikedTweetsParams are the parameters for getting most liked tweets.
type GetMostLikedTweetsParams struct {
	Since time.Time
	Limit int32
}

// GetMostLikedTweetsRow represents a most liked tweet row.
type GetMostLikedTweetsRow struct {
	Tweet     GetTweetByIDRow
	LikeCount int64
}

// GetMostLikedTweets retrieves the most liked tweets.
func (q *Queries) GetMostLikedTweets(ctx context.Context, arg GetMostLikedTweetsParams) ([]*GetMostLikedTweetsRow, error) {
	query := `
		SELECT t.*, COUNT(l.id) AS like_count
		FROM tweets t
		LEFT JOIN likes l ON t.id = l.tweet_id
		WHERE t.deleted_at IS NULL
		  AND t.created_at > $1
		GROUP BY t.id
		ORDER BY like_count DESC, t.created_at DESC
		LIMIT $2
	`
	rows, err := q.db.QueryContext(ctx, query, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetMostLikedTweetsRow
	for rows.Next() {
		var row GetMostLikedTweetsRow
		if err := rows.Scan(
			&row.Tweet.ID, &row.Tweet.UserID, &row.Tweet.Content, pq.Array(&row.Tweet.MediaURLs),
			&row.Tweet.ParentTweetID, &row.Tweet.RetweetOfID, &row.Tweet.IsPoll,
			&row.Tweet.ViewCount, &row.Tweet.CreatedAt, &row.Tweet.UpdatedAt, &row.Tweet.DeletedAt, &row.Tweet.Metadata,
			&row.LikeCount,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// GetMostRetweetedTweetsParams are the parameters for getting most retweeted tweets.
type GetMostRetweetedTweetsParams struct {
	Since time.Time
	Limit int32
}

// GetMostRetweetedTweetsRow represents a most retweeted tweet row.
type GetMostRetweetedTweetsRow struct {
	Tweet        GetTweetByIDRow
	RetweetCount int64
}

// GetMostRetweetedTweets retrieves the most retweeted tweets.
func (q *Queries) GetMostRetweetedTweets(ctx context.Context, arg GetMostRetweetedTweetsParams) ([]*GetMostRetweetedTweetsRow, error) {
	query := `
		SELECT t.*, COUNT(rt.id) AS retweet_count
		FROM tweets t
		LEFT JOIN retweets rt ON t.id = rt.tweet_id
		WHERE t.deleted_at IS NULL
		  AND t.created_at > $1
		GROUP BY t.id
		ORDER BY retweet_count DESC, t.created_at DESC
		LIMIT $2
	`
	rows, err := q.db.QueryContext(ctx, query, arg.Since, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetMostRetweetedTweetsRow
	for rows.Next() {
		var row GetMostRetweetedTweetsRow
		if err := rows.Scan(
			&row.Tweet.ID, &row.Tweet.UserID, &row.Tweet.Content, pq.Array(&row.Tweet.MediaURLs),
			&row.Tweet.ParentTweetID, &row.Tweet.RetweetOfID, &row.Tweet.IsPoll,
			&row.Tweet.ViewCount, &row.Tweet.CreatedAt, &row.Tweet.UpdatedAt, &row.Tweet.DeletedAt, &row.Tweet.Metadata,
			&row.RetweetCount,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// ======================================================================
// Follow Queries
// ======================================================================

// CreateFollow creates a follow relationship.
func (q *Queries) CreateFollow(ctx context.Context, followerID, followeeID string) error {
	query := `INSERT INTO follows (follower_id, followee_id, status, created_at) VALUES ($1, $2, 'accepted', NOW())`
	_, err := q.db.ExecContext(ctx, query, followerID, followeeID)
	return err
}

// DeleteFollow removes a follow relationship.
func (q *Queries) DeleteFollow(ctx context.Context, followerID, followeeID string) error {
	query := `DELETE FROM follows WHERE follower_id = $1 AND followee_id = $2`
	_, err := q.db.ExecContext(ctx, query, followerID, followeeID)
	return err
}

// FollowExists checks if a follow relationship exists.
func (q *Queries) FollowExists(ctx context.Context, followerID, followeeID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM follows WHERE follower_id = $1 AND followee_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, followerID, followeeID).Scan(&exists)
	return exists, err
}

// CountFollowers counts followers of a user.
func (q *Queries) CountFollowers(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM follows WHERE followee_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// CountFollowing counts users followed by a user.
func (q *Queries) CountFollowing(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM follows WHERE follower_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// CountMutualFollows counts mutual follows between two users.
func (q *Queries) CountMutualFollows(ctx context.Context, user1ID, user2ID string) (int64, error) {
	query := `
		SELECT COUNT(*)
		FROM follows f1
		JOIN follows f2 ON f1.followee_id = f2.follower_id
		WHERE f1.follower_id = $1 AND f2.followee_id = $2
	`
	var count int64
	err := q.db.QueryRowContext(ctx, query, user1ID, user2ID).Scan(&count)
	return count, err
}

// GetFollowersParams are the parameters for getting followers.
type GetFollowersParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetFollowers retrieves followers of a user.
func (q *Queries) GetFollowers(ctx context.Context, arg GetFollowersParams) ([]*Follow, error) {
	query := `SELECT f.* FROM follows f WHERE f.followee_id = $1 ORDER BY f.created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var follows []*Follow
	for rows.Next() {
		var f Follow
		if err := rows.Scan(&f.FollowerID, &f.FolloweeID, &f.Status, &f.CreatedAt, &f.UpdatedAt, &f.DeletedAt); err != nil {
			return nil, err
		}
		follows = append(follows, &f)
	}
	return follows, rows.Err()
}

// GetFollowingParams are the parameters for getting following.
type GetFollowingParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetFollowing retrieves users followed by a user.
func (q *Queries) GetFollowing(ctx context.Context, arg GetFollowingParams) ([]*Follow, error) {
	query := `SELECT f.* FROM follows f WHERE f.follower_id = $1 ORDER BY f.created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var follows []*Follow
	for rows.Next() {
		var f Follow
		if err := rows.Scan(&f.FollowerID, &f.FolloweeID, &f.Status, &f.CreatedAt, &f.UpdatedAt, &f.DeletedAt); err != nil {
			return nil, err
		}
		follows = append(follows, &f)
	}
	return follows, rows.Err()
}

// AreMutual checks if two users are mutual follows.
func (q *Queries) AreMutual(ctx context.Context, user1ID, user2ID string) (bool, error) {
	query := `
		SELECT EXISTS(
			SELECT 1 FROM follows f1
			JOIN follows f2 ON f1.followee_id = f2.follower_id
			WHERE f1.follower_id = $1 AND f2.followee_id = $2
		)
	`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, user1ID, user2ID).Scan(&exists)
	return exists, err
}

// GetFollowRecommendationsParams are the parameters for getting follow recommendations.
type GetFollowRecommendationsParams struct {
	UserID string
	Limit  int32
}

// GetFollowRecommendations retrieves follow recommendations for a user.
func (q *Queries) GetFollowRecommendations(ctx context.Context, arg GetFollowRecommendationsParams) ([]string, error) {
	query := `
		SELECT DISTINCT f2.followee_id
		FROM follows f1
		JOIN follows f2 ON f1.followee_id = f2.follower_id
		WHERE f1.follower_id = $1
		  AND f2.followee_id != $1
		  AND f2.followee_id NOT IN (
		    SELECT followee_id FROM follows WHERE follower_id = $1
		  )
		ORDER BY RANDOM()
		LIMIT $2
	`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var ids []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	return ids, rows.Err()
}

// ======================================================================
// Like Queries
// ======================================================================

// CreateLike creates a like.
func (q *Queries) CreateLike(ctx context.Context, tweetID, userID, likeType string) error {
	query := `INSERT INTO likes (tweet_id, user_id, type, created_at) VALUES ($1, $2, $3, NOW())`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID, likeType)
	return err
}

// DeleteLike removes a like.
func (q *Queries) DeleteLike(ctx context.Context, tweetID, userID string) error {
	query := `DELETE FROM likes WHERE tweet_id = $1 AND user_id = $2`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// LikeExists checks if a like exists.
func (q *Queries) LikeExists(ctx context.Context, tweetID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM likes WHERE tweet_id = $1 AND user_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, tweetID, userID).Scan(&exists)
	return exists, err
}

// CountLikes counts likes for a tweet.
func (q *Queries) CountLikes(ctx context.Context, tweetID string) (int64, error) {
	query := `SELECT COUNT(*) FROM likes WHERE tweet_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, tweetID).Scan(&count)
	return count, err
}

// CountLikesByUser counts likes made by a user.
func (q *Queries) CountLikesByUser(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM likes WHERE user_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// GetLikesByTweetIDParams are the parameters for getting likes by tweet ID.
type GetLikesByTweetIDParams struct {
	TweetID string
	Limit   int32
	Offset  int32
}

// GetLikesByTweetIDRow represents a like with user info.
type GetLikesByTweetIDRow struct {
	Like      Like
	Username  string
	FullName  string
	AvatarURL string
}

// GetLikesByTweetID retrieves likes for a tweet with user info.
func (q *Queries) GetLikesByTweetID(ctx context.Context, arg GetLikesByTweetIDParams) ([]*GetLikesByTweetIDRow, error) {
	query := `
		SELECT l.*, u.username, u.full_name, u.avatar_url
		FROM likes l
		JOIN users u ON l.user_id = u.id
		WHERE l.tweet_id = $1
		ORDER BY l.created_at DESC
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.TweetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetLikesByTweetIDRow
	for rows.Next() {
		var row GetLikesByTweetIDRow
		if err := rows.Scan(
			&row.Like.TweetID, &row.Like.UserID, &row.Like.Type, &row.Like.CreatedAt, &row.Like.DeletedAt,
			&row.Username, &row.FullName, &row.AvatarURL,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// GetLikesByUserIDParams are the parameters for getting likes by user ID.
type GetLikesByUserIDParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetLikesByUserID retrieves likes made by a user.
func (q *Queries) GetLikesByUserID(ctx context.Context, arg GetLikesByUserIDParams) ([]*Like, error) {
	query := `SELECT l.* FROM likes l WHERE l.user_id = $1 ORDER BY l.created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var likes []*Like
	for rows.Next() {
		var l Like
		if err := rows.Scan(&l.TweetID, &l.UserID, &l.Type, &l.CreatedAt, &l.DeletedAt); err != nil {
			return nil, err
		}
		likes = append(likes, &l)
	}
	return likes, rows.Err()
}

// ======================================================================
// Retweet Queries
// ======================================================================

// CreateRetweetParams are the parameters for creating a retweet.
type CreateRetweetParams struct {
	TweetID     string
	UserID      string
	Type        string
	QuoteContent string
}

// CreateRetweet creates a retweet.
func (q *Queries) CreateRetweet(ctx context.Context, arg CreateRetweetParams) error {
	query := `INSERT INTO retweets (tweet_id, user_id, type, quote_content, created_at) VALUES ($1, $2, $3, $4, NOW())`
	_, err := q.db.ExecContext(ctx, query, arg.TweetID, arg.UserID, arg.Type, arg.QuoteContent)
	return err
}

// DeleteRetweet removes a retweet.
func (q *Queries) DeleteRetweet(ctx context.Context, tweetID, userID string) error {
	query := `DELETE FROM retweets WHERE tweet_id = $1 AND user_id = $2`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// RetweetExists checks if a retweet exists.
func (q *Queries) RetweetExists(ctx context.Context, tweetID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM retweets WHERE tweet_id = $1 AND user_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, tweetID, userID).Scan(&exists)
	return exists, err
}

// CountRetweets counts retweets for a tweet.
func (q *Queries) CountRetweets(ctx context.Context, tweetID string) (int64, error) {
	query := `SELECT COUNT(*) FROM retweets WHERE tweet_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, tweetID).Scan(&count)
	return count, err
}

// CountRetweetsByUser counts retweets made by a user.
func (q *Queries) CountRetweetsByUser(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM retweets WHERE user_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// GetRetweetsByTweetIDParams are the parameters for getting retweets by tweet ID.
type GetRetweetsByTweetIDParams struct {
	TweetID string
	Limit   int32
	Offset  int32
}

// GetRetweetsByTweetIDRow represents a retweet with user info.
type GetRetweetsByTweetIDRow struct {
	Retweet   Retweet
	Username  string
	FullName  string
	AvatarURL string
}

// GetRetweetsByTweetID retrieves retweets for a tweet with user info.
func (q *Queries) GetRetweetsByTweetID(ctx context.Context, arg GetRetweetsByTweetIDParams) ([]*GetRetweetsByTweetIDRow, error) {
	query := `
		SELECT rt.*, u.username, u.full_name, u.avatar_url
		FROM retweets rt
		JOIN users u ON rt.user_id = u.id
		WHERE rt.tweet_id = $1
		ORDER BY rt.created_at DESC
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.TweetID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetRetweetsByTweetIDRow
	for rows.Next() {
		var row GetRetweetsByTweetIDRow
		if err := rows.Scan(
			&row.Retweet.TweetID, &row.Retweet.UserID, &row.Retweet.Type,
			&row.Retweet.QuoteContent, &row.Retweet.CreatedAt, &row.Retweet.DeletedAt,
			&row.Username, &row.FullName, &row.AvatarURL,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// GetRetweetsByUserIDParams are the parameters for getting retweets by user ID.
type GetRetweetsByUserIDParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetRetweetsByUserID retrieves retweets made by a user.
func (q *Queries) GetRetweetsByUserID(ctx context.Context, arg GetRetweetsByUserIDParams) ([]*Retweet, error) {
	query := `SELECT rt.* FROM retweets rt WHERE rt.user_id = $1 ORDER BY rt.created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var retweets []*Retweet
	for rows.Next() {
		var rt Retweet
		if err := rows.Scan(&rt.TweetID, &rt.UserID, &rt.Type, &rt.QuoteContent, &rt.CreatedAt, &rt.DeletedAt); err != nil {
			return nil, err
		}
		retweets = append(retweets, &rt)
	}
	return retweets, rows.Err()
}

// ======================================================================
// Bookmark Queries
// ======================================================================

// CreateBookmarkParams are the parameters for creating a bookmark.
type CreateBookmarkParams struct {
	TweetID  string
	UserID   string
	Category string
	Name     string
	Notes    string
}

// CreateBookmark creates a bookmark.
func (q *Queries) CreateBookmark(ctx context.Context, arg CreateBookmarkParams) error {
	query := `INSERT INTO bookmarks (tweet_id, user_id, category, name, notes, created_at, updated_at) VALUES ($1, $2, $3, $4, $5, NOW(), NOW())`
	_, err := q.db.ExecContext(ctx, query, arg.TweetID, arg.UserID, arg.Category, arg.Name, arg.Notes)
	return err
}

// DeleteBookmark removes a bookmark.
func (q *Queries) DeleteBookmark(ctx context.Context, tweetID, userID string) error {
	query := `DELETE FROM bookmarks WHERE tweet_id = $1 AND user_id = $2`
	_, err := q.db.ExecContext(ctx, query, tweetID, userID)
	return err
}

// BookmarkExists checks if a bookmark exists.
func (q *Queries) BookmarkExists(ctx context.Context, tweetID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM bookmarks WHERE tweet_id = $1 AND user_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, tweetID, userID).Scan(&exists)
	return exists, err
}

// CountBookmarks counts bookmarks for a tweet.
func (q *Queries) CountBookmarks(ctx context.Context, tweetID string) (int64, error) {
	query := `SELECT COUNT(*) FROM bookmarks WHERE tweet_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, tweetID).Scan(&count)
	return count, err
}

// CountBookmarksByUser counts bookmarks made by a user.
func (q *Queries) CountBookmarksByUser(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM bookmarks WHERE user_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// GetBookmarksByUserIDParams are the parameters for getting bookmarks by user ID.
type GetBookmarksByUserIDParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetBookmarksByUserIDRow represents a bookmark with tweet and user info.
type GetBookmarksByUserIDRow struct {
	Bookmark      Bookmark
	TweetContent  string
	TweetCreatedAt time.Time
	Username      string
	FullName      string
	AvatarURL     string
}

// GetBookmarksByUserID retrieves bookmarks for a user.
func (q *Queries) GetBookmarksByUserID(ctx context.Context, arg GetBookmarksByUserIDParams) ([]*GetBookmarksByUserIDRow, error) {
	query := `
		SELECT b.*, t.content AS tweet_content, t.created_at AS tweet_created_at,
		       u.username, u.full_name, u.avatar_url
		FROM bookmarks b
		JOIN tweets t ON b.tweet_id = t.id
		JOIN users u ON t.user_id = u.id
		WHERE b.user_id = $1
		  AND t.deleted_at IS NULL
		ORDER BY b.created_at DESC
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetBookmarksByUserIDRow
	for rows.Next() {
		var row GetBookmarksByUserIDRow
		if err := rows.Scan(
			&row.Bookmark.TweetID, &row.Bookmark.UserID, &row.Bookmark.Category,
			&row.Bookmark.Name, &row.Bookmark.Notes, &row.Bookmark.Metadata,
			&row.Bookmark.CreatedAt, &row.Bookmark.UpdatedAt, &row.Bookmark.DeletedAt,
			&row.TweetContent, &row.TweetCreatedAt,
			&row.Username, &row.FullName, &row.AvatarURL,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// ======================================================================
// Message Queries
// ======================================================================

// CreateMessageParams are the parameters for creating a message.
type CreateMessageParams struct {
	ID         string
	SenderID   string
	ReceiverID string
	Content    string
	MediaURLs  []string
	Read       bool
	CreatedAt  time.Time
	UpdatedAt  time.Time
}

// CreateMessage creates a direct message.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	query := `
		INSERT INTO messages (
			id, sender_id, receiver_id, content, media_urls,
			read, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.SenderID, arg.ReceiverID, arg.Content,
		pq.Array(arg.MediaURLs), arg.Read, arg.CreatedAt, arg.UpdatedAt,
	)
	return err
}

// GetMessageByIDRow represents a message row.
type GetMessageByIDRow struct {
	ID         string
	SenderID   string
	ReceiverID string
	Content    string
	MediaURLs  []string
	Read       bool
	ReadAt     sql.NullTime
	CreatedAt  time.Time
	UpdatedAt  time.Time
	DeletedAt  sql.NullTime
	Metadata   json.RawMessage
}

// GetMessageByID retrieves a message by ID.
func (q *Queries) GetMessageByID(ctx context.Context, id string) (*GetMessageByIDRow, error) {
	query := `SELECT * FROM messages WHERE id = $1 AND deleted_at IS NULL`
	var row GetMessageByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.SenderID, &row.ReceiverID, &row.Content, pq.Array(&row.MediaURLs),
		&row.Read, &row.ReadAt, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetMessagesBetweenUsersParams are the parameters for getting messages between users.
type GetMessagesBetweenUsersParams struct {
	User1ID string
	User2ID string
	Limit   int32
	Offset  int32
}

// GetMessagesBetweenUsers retrieves messages between two users.
func (q *Queries) GetMessagesBetweenUsers(ctx context.Context, arg GetMessagesBetweenUsersParams) ([]*GetMessageByIDRow, error) {
	query := `
		SELECT * FROM messages
		WHERE (sender_id = $1 AND receiver_id = $2) 
		   OR (sender_id = $2 AND receiver_id = $1)
		  AND deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $3 OFFSET $4
	`
	rows, err := q.db.QueryContext(ctx, query, arg.User1ID, arg.User2ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var messages []*GetMessageByIDRow
	for rows.Next() {
		var row GetMessageByIDRow
		if err := rows.Scan(
			&row.ID, &row.SenderID, &row.ReceiverID, &row.Content, pq.Array(&row.MediaURLs),
			&row.Read, &row.ReadAt, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		messages = append(messages, &row)
	}
	return messages, rows.Err()
}

// GetConversationsRow represents a conversation row.
type GetConversationsRow struct {
	OtherUserID       string
	LastMessageAt     time.Time
	LastMessageID     string
	LastMessageContent string
	LastMessageRead   bool
	UnreadCount       int
}

// GetConversations retrieves all conversations for a user.
func (q *Queries) GetConversations(ctx context.Context, userID string) ([]*GetConversationsRow, error) {
	query := `
		SELECT 
			CASE 
				WHEN sender_id = $1 THEN receiver_id
				WHEN receiver_id = $1 THEN sender_id
			END AS other_user_id,
			MAX(created_at) AS last_message_at,
			(SELECT id FROM messages m2 
			 WHERE (m2.sender_id = $1 AND m2.receiver_id = other_user_id)
				OR (m2.sender_id = other_user_id AND m2.receiver_id = $1)
			   AND m2.deleted_at IS NULL
			 ORDER BY m2.created_at DESC LIMIT 1) AS last_message_id,
			(SELECT content FROM messages m3 WHERE m3.id = last_message_id) AS last_message_content,
			(SELECT read FROM messages m3 WHERE m3.id = last_message_id) AS last_message_read,
			COUNT(CASE WHEN read = false AND receiver_id = $1 THEN 1 END) AS unread_count
		FROM messages
		WHERE (sender_id = $1 OR receiver_id = $1)
		  AND deleted_at IS NULL
		GROUP BY other_user_id
		ORDER BY last_message_at DESC
	`
	rows, err := q.db.QueryContext(ctx, query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetConversationsRow
	for rows.Next() {
		var row GetConversationsRow
		if err := rows.Scan(
			&row.OtherUserID, &row.LastMessageAt, &row.LastMessageID,
			&row.LastMessageContent, &row.LastMessageRead, &row.UnreadCount,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// CountUnreadMessages counts unread messages for a user.
func (q *Queries) CountUnreadMessages(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM messages WHERE receiver_id = $1 AND read = false AND deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// CountUnreadFromUser counts unread messages from a specific user.
func (q *Queries) CountUnreadFromUser(ctx context.Context, userID, senderID string) (int64, error) {
	query := `SELECT COUNT(*) FROM messages WHERE receiver_id = $1 AND sender_id = $2 AND read = false AND deleted_at IS NULL`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID, senderID).Scan(&count)
	return count, err
}

// MarkMessageRead marks a message as read.
func (q *Queries) MarkMessageRead(ctx context.Context, id string) error {
	query := `UPDATE messages SET read = true, read_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// MarkConversationRead marks all messages in a conversation as read.
func (q *Queries) MarkConversationRead(ctx context.Context, userID, otherUserID string) error {
	query := `UPDATE messages SET read = true, read_at = NOW() WHERE receiver_id = $1 AND sender_id = $2 AND read = false`
	_, err := q.db.ExecContext(ctx, query, userID, otherUserID)
	return err
}

// MarkAllMessagesRead marks all messages for a user as read.
func (q *Queries) MarkAllMessagesRead(ctx context.Context, userID string) error {
	query := `UPDATE messages SET read = true, read_at = NOW() WHERE receiver_id = $1 AND read = false`
	_, err := q.db.ExecContext(ctx, query, userID)
	return err
}

// SoftDeleteMessage soft deletes a message.
func (q *Queries) SoftDeleteMessage(ctx context.Context, id string) error {
	query := `UPDATE messages SET deleted_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// HardDeleteMessage permanently deletes a message.
func (q *Queries) HardDeleteMessage(ctx context.Context, id string) error {
	query := `DELETE FROM messages WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// DeleteConversation deletes all messages between two users.
func (q *Queries) DeleteConversation(ctx context.Context, user1ID, user2ID string) error {
	query := `DELETE FROM messages WHERE (sender_id = $1 AND receiver_id = $2) OR (sender_id = $2 AND receiver_id = $1)`
	_, err := q.db.ExecContext(ctx, query, user1ID, user2ID)
	return err
}

// SearchMessagesParams are the parameters for searching messages.
type SearchMessagesParams struct {
	UserID string
	Query  string
	Limit  int32
	Offset int32
}

// SearchMessages searches messages by content.
func (q *Queries) SearchMessages(ctx context.Context, arg SearchMessagesParams) ([]*GetMessageByIDRow, error) {
	query := `
		SELECT * FROM messages
		WHERE (sender_id = $1 OR receiver_id = $1)
		  AND content ILIKE '%' || $2 || '%'
		  AND deleted_at IS NULL
		ORDER BY created_at DESC
		LIMIT $3 OFFSET $4
	`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var messages []*GetMessageByIDRow
	for rows.Next() {
		var row GetMessageByIDRow
		if err := rows.Scan(
			&row.ID, &row.SenderID, &row.ReceiverID, &row.Content, pq.Array(&row.MediaURLs),
			&row.Read, &row.ReadAt, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		messages = append(messages, &row)
	}
	return messages, rows.Err()
}

// ======================================================================
// Notification Queries
// ======================================================================

// CreateNotificationParams are the parameters for creating a notification.
type CreateNotificationParams struct {
	ID          string
	UserID      string
	FromUserID  string
	Type        string
	ReferenceID string
	Read        bool
}

// CreateNotification creates a notification.
func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) error {
	query := `
		INSERT INTO notifications (
			id, user_id, from_user_id, type, reference_id, read, created_at
		) VALUES ($1, $2, $3, $4, $5, $6, NOW())
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.UserID, arg.FromUserID, arg.Type, arg.ReferenceID, arg.Read,
	)
	return err
}

// GetNotificationByIDRow represents a notification row.
type GetNotificationByIDRow struct {
	ID          string
	UserID      string
	FromUserID  string
	Type        string
	ReferenceID string
	Read        bool
	ReadAt      sql.NullTime
	CreatedAt   time.Time
	Metadata    json.RawMessage
}

// GetNotificationByID retrieves a notification by ID.
func (q *Queries) GetNotificationByID(ctx context.Context, id string) (*GetNotificationByIDRow, error) {
	query := `SELECT * FROM notifications WHERE id = $1`
	var row GetNotificationByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.UserID, &row.FromUserID, &row.Type, &row.ReferenceID,
		&row.Read, &row.ReadAt, &row.CreatedAt, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetNotificationsByUserIDParams are the parameters for getting notifications.
type GetNotificationsByUserIDParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetNotificationsByUserID retrieves notifications for a user.
func (q *Queries) GetNotificationsByUserID(ctx context.Context, arg GetNotificationsByUserIDParams) ([]*GetNotificationByIDRow, error) {
	query := `SELECT * FROM notifications WHERE user_id = $1 ORDER BY created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var notifications []*GetNotificationByIDRow
	for rows.Next() {
		var row GetNotificationByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.FromUserID, &row.Type, &row.ReferenceID,
			&row.Read, &row.ReadAt, &row.CreatedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		notifications = append(notifications, &row)
	}
	return notifications, rows.Err()
}

// GetUnreadNotificationsParams are the parameters for getting unread notifications.
type GetUnreadNotificationsParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetUnreadNotifications retrieves unread notifications for a user.
func (q *Queries) GetUnreadNotifications(ctx context.Context, arg GetUnreadNotificationsParams) ([]*GetNotificationByIDRow, error) {
	query := `SELECT * FROM notifications WHERE user_id = $1 AND read = false ORDER BY created_at DESC LIMIT $2 OFFSET $3`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var notifications []*GetNotificationByIDRow
	for rows.Next() {
		var row GetNotificationByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.FromUserID, &row.Type, &row.ReferenceID,
			&row.Read, &row.ReadAt, &row.CreatedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		notifications = append(notifications, &row)
	}
	return notifications, rows.Err()
}

// CountUnreadNotifications counts unread notifications for a user.
func (q *Queries) CountUnreadNotifications(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read = false`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// CountNotificationsByUser counts all notifications for a user.
func (q *Queries) CountNotificationsByUser(ctx context.Context, userID string) (int64, error) {
	query := `SELECT COUNT(*) FROM notifications WHERE user_id = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID).Scan(&count)
	return count, err
}

// MarkNotificationRead marks a notification as read.
func (q *Queries) MarkNotificationRead(ctx context.Context, id string) error {
	query := `UPDATE notifications SET read = true, read_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// MarkAllNotificationsRead marks all notifications for a user as read.
func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID string) error {
	query := `UPDATE notifications SET read = true, read_at = NOW() WHERE user_id = $1 AND read = false`
	_, err := q.db.ExecContext(ctx, query, userID)
	return err
}

// MarkMultipleNotificationsReadParams are the parameters for marking multiple notifications as read.
type MarkMultipleNotificationsReadParams struct {
	IDs []string
}

// MarkMultipleNotificationsRead marks multiple notifications as read.
func (q *Queries) MarkMultipleNotificationsRead(ctx context.Context, arg MarkMultipleNotificationsReadParams) error {
	query := `UPDATE notifications SET read = true, read_at = NOW() WHERE id = ANY($1::text[])`
	_, err := q.db.ExecContext(ctx, query, pq.Array(arg.IDs))
	return err
}

// DeleteNotification deletes a notification.
func (q *Queries) DeleteNotification(ctx context.Context, id string) error {
	query := `DELETE FROM notifications WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// DeleteAllNotifications deletes all notifications for a user.
func (q *Queries) DeleteAllNotifications(ctx context.Context, userID string) error {
	query := `DELETE FROM notifications WHERE user_id = $1`
	_, err := q.db.ExecContext(ctx, query, userID)
	return err
}

// GetNotificationsByTypeParams are the parameters for getting notifications by type.
type GetNotificationsByTypeParams struct {
	UserID string
	Type   string
	Limit  int32
	Offset int32
}

// GetNotificationsByType retrieves notifications by type for a user.
func (q *Queries) GetNotificationsByType(ctx context.Context, arg GetNotificationsByTypeParams) ([]*GetNotificationByIDRow, error) {
	query := `SELECT * FROM notifications WHERE user_id = $1 AND type = $2 ORDER BY created_at DESC LIMIT $3 OFFSET $4`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Type, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var notifications []*GetNotificationByIDRow
	for rows.Next() {
		var row GetNotificationByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.FromUserID, &row.Type, &row.ReferenceID,
			&row.Read, &row.ReadAt, &row.CreatedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		notifications = append(notifications, &row)
	}
	return notifications, rows.Err()
}

// CountNotificationsByType counts notifications by type for a user.
func (q *Queries) CountNotificationsByType(ctx context.Context, userID, notifType string) (int64, error) {
	query := `SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND type = $2`
	var count int64
	err := q.db.QueryRowContext(ctx, query, userID, notifType).Scan(&count)
	return count, err
}

// GroupNotificationsByTypeRow represents a grouped notification row.
type GroupNotificationsByTypeRow struct {
	Type       string
	Count      int64
	LatestAt   time.Time
	ReadCount  int64
	UnreadCount int64
}

// GroupNotificationsByType groups notifications by type.
func (q *Queries) GroupNotificationsByType(ctx context.Context, userID string) ([]*GroupNotificationsByTypeRow, error) {
	query := `
		SELECT 
			type,
			COUNT(*) AS count,
			MAX(created_at) AS latest_at,
			SUM(CASE WHEN read = true THEN 1 ELSE 0 END) AS read_count,
			SUM(CASE WHEN read = false THEN 1 ELSE 0 END) AS unread_count
		FROM notifications
		WHERE user_id = $1
		GROUP BY type
		ORDER BY latest_at DESC
	`
	rows, err := q.db.QueryContext(ctx, query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GroupNotificationsByTypeRow
	for rows.Next() {
		var row GroupNotificationsByTypeRow
		if err := rows.Scan(&row.Type, &row.Count, &row.LatestAt, &row.ReadCount, &row.UnreadCount); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// ======================================================================
// Poll Queries
// ======================================================================

// CreatePollParams are the parameters for creating a poll.
type CreatePollParams struct {
	ID        string
	TweetID   string
	Options   json.RawMessage
	Duration  int64
	ExpiresAt time.Time
}

// CreatePoll creates a poll.
func (q *Queries) CreatePoll(ctx context.Context, arg CreatePollParams) error {
	query := `
		INSERT INTO polls (
			id, tweet_id, options, duration, expires_at, created_at
		) VALUES ($1, $2, $3, $4, $5, NOW())
	`
	_, err := q.db.ExecContext(ctx, query, arg.ID, arg.TweetID, arg.Options, arg.Duration, arg.ExpiresAt)
	return err
}

// GetPollByIDRow represents a poll row.
type GetPollByIDRow struct {
	ID        string
	TweetID   string
	Question  string
	Options   json.RawMessage
	Duration  int64
	ExpiresAt time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}

// GetPollByID retrieves a poll by ID.
func (q *Queries) GetPollByID(ctx context.Context, id string) (*GetPollByIDRow, error) {
	query := `SELECT * FROM polls WHERE id = $1`
	var row GetPollByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.TweetID, &row.Question, &row.Options,
		&row.Duration, &row.ExpiresAt, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetPollByTweetID retrieves a poll by tweet ID.
func (q *Queries) GetPollByTweetID(ctx context.Context, tweetID string) (*GetPollByIDRow, error) {
	query := `SELECT * FROM polls WHERE tweet_id = $1`
	var row GetPollByIDRow
	err := q.db.QueryRowContext(ctx, query, tweetID).Scan(
		&row.ID, &row.TweetID, &row.Question, &row.Options,
		&row.Duration, &row.ExpiresAt, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// UpdatePoll updates a poll.
func (q *Queries) UpdatePoll(ctx context.Context, pollID string, options json.RawMessage) error {
	query := `UPDATE polls SET options = $1, updated_at = NOW() WHERE id = $2`
	_, err := q.db.ExecContext(ctx, query, options, pollID)
	return err
}

// DeletePoll deletes a poll.
func (q *Queries) DeletePoll(ctx context.Context, id string) error {
	query := `DELETE FROM polls WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// GetExpiredPolls retrieves expired polls.
func (q *Queries) GetExpiredPolls(ctx context.Context) ([]*GetPollByIDRow, error) {
	query := `SELECT * FROM polls WHERE expires_at <= NOW() AND deleted_at IS NULL`
	rows, err := q.db.QueryContext(ctx, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var polls []*GetPollByIDRow
	for rows.Next() {
		var row GetPollByIDRow
		if err := rows.Scan(
			&row.ID, &row.TweetID, &row.Question, &row.Options,
			&row.Duration, &row.ExpiresAt, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt,
		); err != nil {
			return nil, err
		}
		polls = append(polls, &row)
	}
	return polls, rows.Err()
}

// ======================================================================
// Community Queries
// ======================================================================

// CreateCommunityParams are the parameters for creating a community.
type CreateCommunityParams struct {
	ID          string
	Name        string
	Slug        string
	Description string
	AvatarURL   string
	BannerURL   string
	CreatedBy   string
	IsPrivate   bool
	MemberCount int64
	PostCount   int64
}

// CreateCommunity creates a community.
func (q *Queries) CreateCommunity(ctx context.Context, arg CreateCommunityParams) error {
	query := `
		INSERT INTO communities (
			id, name, slug, description, avatar_url, banner_url,
			created_by, is_private, member_count, post_count, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, NOW(), NOW())
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.Name, arg.Slug, arg.Description, arg.AvatarURL,
		arg.BannerURL, arg.CreatedBy, arg.IsPrivate, arg.MemberCount, arg.PostCount,
	)
	return err
}

// GetCommunityByIDRow represents a community row.
type GetCommunityByIDRow struct {
	ID          string
	Name        string
	Slug        string
	Description string
	AvatarURL   string
	BannerURL   string
	CreatedBy   string
	IsPrivate   bool
	Status      string
	MemberCount int64
	PostCount   int64
	CreatedAt   time.Time
	UpdatedAt   time.Time
	DeletedAt   sql.NullTime
	Settings    json.RawMessage
	Tags        []string
}

// GetCommunityByID retrieves a community by ID.
func (q *Queries) GetCommunityByID(ctx context.Context, id string) (*GetCommunityByIDRow, error) {
	query := `SELECT * FROM communities WHERE id = $1 AND deleted_at IS NULL`
	var row GetCommunityByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.Name, &row.Slug, &row.Description, &row.AvatarURL,
		&row.BannerURL, &row.CreatedBy, &row.IsPrivate, &row.Status,
		&row.MemberCount, &row.PostCount, &row.CreatedAt, &row.UpdatedAt,
		&row.DeletedAt, &row.Settings, pq.Array(&row.Tags),
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetCommunityBySlug retrieves a community by slug.
func (q *Queries) GetCommunityBySlug(ctx context.Context, slug string) (*GetCommunityByIDRow, error) {
	query := `SELECT * FROM communities WHERE slug = $1 AND deleted_at IS NULL`
	var row GetCommunityByIDRow
	err := q.db.QueryRowContext(ctx, query, slug).Scan(
		&row.ID, &row.Name, &row.Slug, &row.Description, &row.AvatarURL,
		&row.BannerURL, &row.CreatedBy, &row.IsPrivate, &row.Status,
		&row.MemberCount, &row.PostCount, &row.CreatedAt, &row.UpdatedAt,
		&row.DeletedAt, &row.Settings, pq.Array(&row.Tags),
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// UpdateCommunity updates a community.
func (q *Queries) UpdateCommunity(ctx context.Context, arg GetCommunityByIDRow) error {
	query := `
		UPDATE communities SET
			name = $1,
			description = $2,
			avatar_url = $3,
			banner_url = $4,
			is_private = $5,
			updated_at = NOW()
		WHERE id = $6 AND deleted_at IS NULL
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.Name, arg.Description, arg.AvatarURL, arg.BannerURL,
		arg.IsPrivate, arg.ID,
	)
	return err
}

// SoftDeleteCommunity soft deletes a community.
func (q *Queries) SoftDeleteCommunity(ctx context.Context, id string) error {
	query := `UPDATE communities SET deleted_at = NOW() WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// ListCommunitiesParams are the parameters for listing communities.
type ListCommunitiesParams struct {
	Limit  int32
	Offset int32
}

// ListCommunities retrieves a list of communities.
func (q *Queries) ListCommunities(ctx context.Context, arg ListCommunitiesParams) ([]*GetCommunityByIDRow, error) {
	query := `SELECT * FROM communities WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT $1 OFFSET $2`
	rows, err := q.db.QueryContext(ctx, query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var communities []*GetCommunityByIDRow
	for rows.Next() {
		var row GetCommunityByIDRow
		if err := rows.Scan(
			&row.ID, &row.Name, &row.Slug, &row.Description, &row.AvatarURL,
			&row.BannerURL, &row.CreatedBy, &row.IsPrivate, &row.Status,
			&row.MemberCount, &row.PostCount, &row.CreatedAt, &row.UpdatedAt,
			&row.DeletedAt, &row.Settings, pq.Array(&row.Tags),
		); err != nil {
			return nil, err
		}
		communities = append(communities, &row)
	}
	return communities, rows.Err()
}

// SearchCommunitiesParams are the parameters for searching communities.
type SearchCommunitiesParams struct {
	Query  string
	Limit  int32
	Offset int32
}

// SearchCommunities searches for communities.
func (q *Queries) SearchCommunities(ctx context.Context, arg SearchCommunitiesParams) ([]*GetCommunityByIDRow, error) {
	query := `
		SELECT * FROM communities
		WHERE deleted_at IS NULL
		  AND (name ILIKE '%' || $1 || '%' 
		    OR description ILIKE '%' || $1 || '%')
		ORDER BY name
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.Query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var communities []*GetCommunityByIDRow
	for rows.Next() {
		var row GetCommunityByIDRow
		if err := rows.Scan(
			&row.ID, &row.Name, &row.Slug, &row.Description, &row.AvatarURL,
			&row.BannerURL, &row.CreatedBy, &row.IsPrivate, &row.Status,
			&row.MemberCount, &row.PostCount, &row.CreatedAt, &row.UpdatedAt,
			&row.DeletedAt, &row.Settings, pq.Array(&row.Tags),
		); err != nil {
			return nil, err
		}
		communities = append(communities, &row)
	}
	return communities, rows.Err()
}

// AddCommunityMember adds a member to a community.
func (q *Queries) AddCommunityMember(ctx context.Context, communityID, userID, role string) error {
	query := `INSERT INTO community_members (community_id, user_id, role, joined_at) VALUES ($1, $2, $3, NOW())`
	_, err := q.db.ExecContext(ctx, query, communityID, userID, role)
	if err != nil {
		return err
	}
	// Increment member count
	_, err = q.db.ExecContext(ctx, `UPDATE communities SET member_count = member_count + 1 WHERE id = $1`, communityID)
	return err
}

// RemoveCommunityMember removes a member from a community.
func (q *Queries) RemoveCommunityMember(ctx context.Context, communityID, userID string) error {
	query := `DELETE FROM community_members WHERE community_id = $1 AND user_id = $2`
	_, err := q.db.ExecContext(ctx, query, communityID, userID)
	if err != nil {
		return err
	}
	// Decrement member count
	_, err = q.db.ExecContext(ctx, `UPDATE communities SET member_count = GREATEST(member_count - 1, 0) WHERE id = $1`, communityID)
	return err
}

// UpdateCommunityMemberRole updates a member's role.
func (q *Queries) UpdateCommunityMemberRole(ctx context.Context, communityID, userID, role string) error {
	query := `UPDATE community_members SET role = $1, updated_at = NOW() WHERE community_id = $2 AND user_id = $3`
	_, err := q.db.ExecContext(ctx, query, role, communityID, userID)
	return err
}

// GetCommunityMemberRole gets a member's role.
func (q *Queries) GetCommunityMemberRole(ctx context.Context, communityID, userID string) (string, error) {
	query := `SELECT role FROM community_members WHERE community_id = $1 AND user_id = $2`
	var role string
	err := q.db.QueryRowContext(ctx, query, communityID, userID).Scan(&role)
	return role, err
}

// IsCommunityMember checks if a user is a member of a community.
func (q *Queries) IsCommunityMember(ctx context.Context, communityID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM community_members WHERE community_id = $1 AND user_id = $2)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, communityID, userID).Scan(&exists)
	return exists, err
}

// IsCommunityAdmin checks if a user is an admin of a community.
func (q *Queries) IsCommunityAdmin(ctx context.Context, communityID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM community_members WHERE community_id = $1 AND user_id = $2 AND role IN ('admin', 'owner'))`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, communityID, userID).Scan(&exists)
	return exists, err
}

// GetCommunityMembersParams are the parameters for getting community members.
type GetCommunityMembersParams struct {
	CommunityID string
	Limit       int32
	Offset      int32
}

// GetCommunityMembersRow represents a community member row with user info.
type GetCommunityMembersRow struct {
	CommunityMember CommunityMember
	Username        string
	FullName        string
	AvatarURL       string
}

// GetCommunityMembers retrieves members of a community.
func (q *Queries) GetCommunityMembers(ctx context.Context, arg GetCommunityMembersParams) ([]*GetCommunityMembersRow, error) {
	query := `
		SELECT cm.*, u.username, u.full_name, u.avatar_url
		FROM community_members cm
		JOIN users u ON cm.user_id = u.id
		WHERE cm.community_id = $1
		ORDER BY cm.joined_at DESC
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.CommunityID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetCommunityMembersRow
	for rows.Next() {
		var row GetCommunityMembersRow
		if err := rows.Scan(
			&row.CommunityMember.CommunityID, &row.CommunityMember.UserID,
			&row.CommunityMember.Role, &row.CommunityMember.JoinedAt, &row.CommunityMember.UpdatedAt,
			&row.Username, &row.FullName, &row.AvatarURL,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// GetUserCommunitiesParams are the parameters for getting user communities.
type GetUserCommunitiesParams struct {
	UserID string
	Limit  int32
	Offset int32
}

// GetUserCommunities retrieves communities a user is a member of.
func (q *Queries) GetUserCommunities(ctx context.Context, arg GetUserCommunitiesParams) ([]*GetCommunityByIDRow, error) {
	query := `
		SELECT c.*
		FROM communities c
		JOIN community_members cm ON c.id = cm.community_id
		WHERE cm.user_id = $1 AND c.deleted_at IS NULL
		ORDER BY cm.joined_at DESC
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var communities []*GetCommunityByIDRow
	for rows.Next() {
		var row GetCommunityByIDRow
		if err := rows.Scan(
			&row.ID, &row.Name, &row.Slug, &row.Description, &row.AvatarURL,
			&row.BannerURL, &row.CreatedBy, &row.IsPrivate, &row.Status,
			&row.MemberCount, &row.PostCount, &row.CreatedAt, &row.UpdatedAt,
			&row.DeletedAt, &row.Settings, pq.Array(&row.Tags),
		); err != nil {
			return nil, err
		}
		communities = append(communities, &row)
	}
	return communities, rows.Err()
}

// AddCommunityPost adds a post to a community.
func (q *Queries) AddCommunityPost(ctx context.Context, communityID, tweetID string) error {
	query := `INSERT INTO community_posts (community_id, tweet_id, created_at) VALUES ($1, $2, NOW())`
	_, err := q.db.ExecContext(ctx, query, communityID, tweetID)
	if err != nil {
		return err
	}
	// Increment post count
	_, err = q.db.ExecContext(ctx, `UPDATE communities SET post_count = post_count + 1 WHERE id = $1`, communityID)
	return err
}

// RemoveCommunityPost removes a post from a community.
func (q *Queries) RemoveCommunityPost(ctx context.Context, communityID, tweetID string) error {
	query := `DELETE FROM community_posts WHERE community_id = $1 AND tweet_id = $2`
	_, err := q.db.ExecContext(ctx, query, communityID, tweetID)
	if err != nil {
		return err
	}
	// Decrement post count
	_, err = q.db.ExecContext(ctx, `UPDATE communities SET post_count = GREATEST(post_count - 1, 0) WHERE id = $1`, communityID)
	return err
}

// GetCommunityPostsParams are the parameters for getting community posts.
type GetCommunityPostsParams struct {
	CommunityID string
	Limit       int32
	Offset      int32
}

// GetCommunityPosts retrieves posts in a community.
func (q *Queries) GetCommunityPosts(ctx context.Context, arg GetCommunityPostsParams) ([]*GetTweetByIDRow, error) {
	query := `
		SELECT t.*
		FROM community_posts cp
		JOIN tweets t ON cp.tweet_id = t.id
		WHERE cp.community_id = $1 AND t.deleted_at IS NULL
		ORDER BY cp.created_at DESC
		LIMIT $2 OFFSET $3
	`
	rows, err := q.db.QueryContext(ctx, query, arg.CommunityID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var tweets []*GetTweetByIDRow
	for rows.Next() {
		var row GetTweetByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.Content, pq.Array(&row.MediaURLs),
			&row.ParentTweetID, &row.RetweetOfID, &row.IsPoll,
			&row.ViewCount, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		tweets = append(tweets, &row)
	}
	return tweets, rows.Err()
}

// ======================================================================
// Report Queries
// ======================================================================

// CreateReportParams are the parameters for creating a report.
type CreateReportParams struct {
	ID          string
	ReporterID  string
	TargetID    string
	TargetType  string
	Reason      string
	Description string
	Status      string
	Severity    string
}

// CreateReport creates a report.
func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) error {
	query := `
		INSERT INTO reports (
			id, reporter_id, target_id, target_type, reason,
			description, status, severity, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), NOW())
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.ReporterID, arg.TargetID, arg.TargetType,
		arg.Reason, arg.Description, arg.Status, arg.Severity,
	)
	return err
}

// GetReportByIDRow represents a report row.
type GetReportByIDRow struct {
	ID          string
	ReporterID  string
	TargetID    string
	TargetType  string
	Type        string
	Reason      string
	Description string
	Status      string
	Severity    string
	ReviewerID  string
	ReviewNotes string
	ResolvedAt  sql.NullTime
	CreatedAt   time.Time
	UpdatedAt   time.Time
	Metadata    json.RawMessage
}

// GetReportByID retrieves a report by ID.
func (q *Queries) GetReportByID(ctx context.Context, id string) (*GetReportByIDRow, error) {
	query := `SELECT * FROM reports WHERE id = $1`
	var row GetReportByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.ReporterID, &row.TargetID, &row.TargetType,
		&row.Type, &row.Reason, &row.Description, &row.Status,
		&row.Severity, &row.ReviewerID, &row.ReviewNotes, &row.ResolvedAt,
		&row.CreatedAt, &row.UpdatedAt, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// ListReportsParams are the parameters for listing reports.
type ListReportsParams struct {
	Limit  int32
	Offset int32
}

// ListReports retrieves a list of reports.
func (q *Queries) ListReports(ctx context.Context, arg ListReportsParams) ([]*GetReportByIDRow, error) {
	query := `SELECT * FROM reports ORDER BY created_at DESC LIMIT $1 OFFSET $2`
	rows, err := q.db.QueryContext(ctx, query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var reports []*GetReportByIDRow
	for rows.Next() {
		var row GetReportByIDRow
		if err := rows.Scan(
			&row.ID, &row.ReporterID, &row.TargetID, &row.TargetType,
			&row.Type, &row.Reason, &row.Description, &row.Status,
			&row.Severity, &row.ReviewerID, &row.ReviewNotes, &row.ResolvedAt,
			&row.CreatedAt, &row.UpdatedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		reports = append(reports, &row)
	}
	return reports, rows.Err()
}

// UpdateReportStatus updates the status of a report.
func (q *Queries) UpdateReportStatus(ctx context.Context, id, status, reviewerID, notes string) error {
	query := `
		UPDATE reports SET
			status = $1,
			reviewer_id = $2,
			review_notes = $3,
			resolved_at = NOW(),
			updated_at = NOW()
		WHERE id = $4
	`
	_, err := q.db.ExecContext(ctx, query, status, reviewerID, notes, id)
	return err
}

// CountReportsByStatus counts reports by status.
func (q *Queries) CountReportsByStatus(ctx context.Context, status string) (int64, error) {
	query := `SELECT COUNT(*) FROM reports WHERE status = $1`
	var count int64
	err := q.db.QueryRowContext(ctx, query, status).Scan(&count)
	return count, err
}

// ======================================================================
// Session Queries
// ======================================================================

// CreateSessionParams are the parameters for creating a session.
type CreateSessionParams struct {
	ID           string
	UserID       string
	RefreshToken string
	UserAgent    string
	IP           string
	ExpiresAt    time.Time
}

// CreateSession creates a session.
func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	query := `
		INSERT INTO sessions (
			id, user_id, refresh_token, user_agent, ip,
			expires_at, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.UserID, arg.RefreshToken, arg.UserAgent, arg.IP, arg.ExpiresAt,
	)
	return err
}

// GetSessionByIDRow represents a session row.
type GetSessionByIDRow struct {
	ID           string
	UserID       string
	RefreshToken string
	Status       string
	Type         string
	UserAgent    string
	IP           string
	DeviceID     string
	DeviceName   string
	OS           string
	Browser      string
	Location     string
	ExpiresAt    time.Time
	LastActive   sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
	Metadata     json.RawMessage
}

// GetSessionByID retrieves a session by ID.
func (q *Queries) GetSessionByID(ctx context.Context, id string) (*GetSessionByIDRow, error) {
	query := `SELECT * FROM sessions WHERE id = $1`
	var row GetSessionByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.UserID, &row.RefreshToken, &row.Status, &row.Type,
		&row.UserAgent, &row.IP, &row.DeviceID, &row.DeviceName,
		&row.OS, &row.Browser, &row.Location, &row.ExpiresAt,
		&row.LastActive, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetSessionByRefreshToken retrieves a session by refresh token.
func (q *Queries) GetSessionByRefreshToken(ctx context.Context, refreshToken string) (*GetSessionByIDRow, error) {
	query := `SELECT * FROM sessions WHERE refresh_token = $1`
	var row GetSessionByIDRow
	err := q.db.QueryRowContext(ctx, query, refreshToken).Scan(
		&row.ID, &row.UserID, &row.RefreshToken, &row.Status, &row.Type,
		&row.UserAgent, &row.IP, &row.DeviceID, &row.DeviceName,
		&row.OS, &row.Browser, &row.Location, &row.ExpiresAt,
		&row.LastActive, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// GetSessionsByUserID retrieves sessions for a user.
func (q *Queries) GetSessionsByUserID(ctx context.Context, userID string) ([]*GetSessionByIDRow, error) {
	query := `SELECT * FROM sessions WHERE user_id = $1 ORDER BY created_at DESC`
	rows, err := q.db.QueryContext(ctx, query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var sessions []*GetSessionByIDRow
	for rows.Next() {
		var row GetSessionByIDRow
		if err := rows.Scan(
			&row.ID, &row.UserID, &row.RefreshToken, &row.Status, &row.Type,
			&row.UserAgent, &row.IP, &row.DeviceID, &row.DeviceName,
			&row.OS, &row.Browser, &row.Location, &row.ExpiresAt,
			&row.LastActive, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		sessions = append(sessions, &row)
	}
	return sessions, rows.Err()
}

// UpdateSession updates a session.
func (q *Queries) UpdateSession(ctx context.Context, arg GetSessionByIDRow) error {
	query := `
		UPDATE sessions SET
			refresh_token = $1,
			expires_at = $2,
			updated_at = NOW()
		WHERE id = $3
	`
	_, err := q.db.ExecContext(ctx, query, arg.RefreshToken, arg.ExpiresAt, arg.ID)
	return err
}

// DeleteSession deletes a session.
func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	query := `DELETE FROM sessions WHERE id = $1`
	_, err := q.db.ExecContext(ctx, query, id)
	return err
}

// DeleteSessionsByUserID deletes all sessions for a user.
func (q *Queries) DeleteSessionsByUserID(ctx context.Context, userID string) error {
	query := `DELETE FROM sessions WHERE user_id = $1`
	_, err := q.db.ExecContext(ctx, query, userID)
	return err
}

// CleanupExpiredSessions deletes all expired sessions.
func (q *Queries) CleanupExpiredSessions(ctx context.Context) error {
	query := `DELETE FROM sessions WHERE expires_at <= NOW()`
	_, err := q.db.ExecContext(ctx, query)
	return err
}

// ======================================================================
// Space Queries
// ======================================================================

// CreateSpaceParams are the parameters for creating a space.
type CreateSpaceParams struct {
	ID           string
	Title        string
	Description  string
	Topic        string
	CreatedBy    string
	Visibility   string
	Type         string
	Status       string
	ScheduledAt  sql.NullTime
	Duration     int64
	MaxListeners int64
	InviteCode   string
}

// CreateSpace creates a space.
func (q *Queries) CreateSpace(ctx context.Context, arg CreateSpaceParams) error {
	query := `
		INSERT INTO spaces (
			id, title, description, topic, created_by,
			visibility, type, status, scheduled_at, duration,
			max_listeners, invite_code, created_at, updated_at
		) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, NOW(), NOW())
	`
	_, err := q.db.ExecContext(ctx, query,
		arg.ID, arg.Title, arg.Description, arg.Topic, arg.CreatedBy,
		arg.Visibility, arg.Type, arg.Status, arg.ScheduledAt,
		arg.Duration, arg.MaxListeners, arg.InviteCode,
	)
	return err
}

// GetSpaceByIDRow represents a space row.
type GetSpaceByIDRow struct {
	ID           string
	Title        string
	Description  string
	Topic        string
	CreatedBy    string
	Visibility   string
	Type         string
	Status       string
	ScheduledAt  sql.NullTime
	StartedAt    sql.NullTime
	EndedAt      sql.NullTime
	Duration     int64
	SpeakerCount int64
	ListenerCount int64
	MaxListeners int64
	InviteCode   string
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    sql.NullTime
	Metadata     json.RawMessage
}

// GetSpaceByID retrieves a space by ID.
func (q *Queries) GetSpaceByID(ctx context.Context, id string) (*GetSpaceByIDRow, error) {
	query := `SELECT * FROM spaces WHERE id = $1 AND deleted_at IS NULL`
	var row GetSpaceByIDRow
	err := q.db.QueryRowContext(ctx, query, id).Scan(
		&row.ID, &row.Title, &row.Description, &row.Topic, &row.CreatedBy,
		&row.Visibility, &row.Type, &row.Status, &row.ScheduledAt,
		&row.StartedAt, &row.EndedAt, &row.Duration,
		&row.SpeakerCount, &row.ListenerCount, &row.MaxListeners,
		&row.InviteCode, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
	)
	if err != nil {
		return nil, err
	}
	return &row, nil
}

// ListSpacesParams are the parameters for listing spaces.
type ListSpacesParams struct {
	Limit  int32
	Offset int32
}

// ListSpaces retrieves a list of spaces.
func (q *Queries) ListSpaces(ctx context.Context, arg ListSpacesParams) ([]*GetSpaceByIDRow, error) {
	query := `SELECT * FROM spaces WHERE deleted_at IS NULL ORDER BY created_at DESC LIMIT $1 OFFSET $2`
	rows, err := q.db.QueryContext(ctx, query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var spaces []*GetSpaceByIDRow
	for rows.Next() {
		var row GetSpaceByIDRow
		if err := rows.Scan(
			&row.ID, &row.Title, &row.Description, &row.Topic, &row.CreatedBy,
			&row.Visibility, &row.Type, &row.Status, &row.ScheduledAt,
			&row.StartedAt, &row.EndedAt, &row.Duration,
			&row.SpeakerCount, &row.ListenerCount, &row.MaxListeners,
			&row.InviteCode, &row.CreatedAt, &row.UpdatedAt, &row.DeletedAt, &row.Metadata,
		); err != nil {
			return nil, err
		}
		spaces = append(spaces, &row)
	}
	return spaces, rows.Err()
}

// UpdateSpaceStatus updates the status of a space.
func (q *Queries) UpdateSpaceStatus(ctx context.Context, id, status string) error {
	query := `UPDATE spaces SET status = $1, updated_at = NOW() WHERE id = $2`
	_, err := q.db.ExecContext(ctx, query, status, id)
	return err
}

// AddSpaceParticipant adds a participant to a space.
func (q *Queries) AddSpaceParticipant(ctx context.Context, spaceID, userID, role, status string, isHost bool) error {
	query := `
		INSERT INTO space_participants (space_id, user_id, role, status, joined_at, is_host)
		VALUES ($1, $2, $3, $4, NOW(), $5)
	`
	_, err := q.db.ExecContext(ctx, query, spaceID, userID, role, status, isHost)
	if err != nil {
		return err
	}
	// Update counts
	if role == "speaker" {
		_, err = q.db.ExecContext(ctx, `UPDATE spaces SET speaker_count = speaker_count + 1 WHERE id = $1`, spaceID)
	} else {
		_, err = q.db.ExecContext(ctx, `UPDATE spaces SET listener_count = listener_count + 1 WHERE id = $1`, spaceID)
	}
	return err
}

// RemoveSpaceParticipant removes a participant from a space.
func (q *Queries) RemoveSpaceParticipant(ctx context.Context, spaceID, userID string) error {
	// Get role before removing
	var role string
	err := q.db.QueryRowContext(ctx, `SELECT role FROM space_participants WHERE space_id = $1 AND user_id = $2 AND left_at IS NULL`, spaceID, userID).Scan(&role)
	if err != nil {
		return err
	}
	query := `UPDATE space_participants SET left_at = NOW() WHERE space_id = $1 AND user_id = $2`
	_, err = q.db.ExecContext(ctx, query, spaceID, userID)
	if err != nil {
		return err
	}
	// Update counts
	if role == "speaker" {
		_, err = q.db.ExecContext(ctx, `UPDATE spaces SET speaker_count = GREATEST(speaker_count - 1, 0) WHERE id = $1`, spaceID)
	} else {
		_, err = q.db.ExecContext(ctx, `UPDATE spaces SET listener_count = GREATEST(listener_count - 1, 0) WHERE id = $1`, spaceID)
	}
	return err
}

// GetSpaceParticipantsParams are the parameters for getting space participants.
type GetSpaceParticipantsParams struct {
	SpaceID string
}

// GetSpaceParticipantsRow represents a space participant row with user info.
type GetSpaceParticipantsRow struct {
	SpaceParticipant SpaceParticipant
	Username         string
	FullName         string
	AvatarURL        string
}

// GetSpaceParticipants retrieves participants of a space.
func (q *Queries) GetSpaceParticipants(ctx context.Context, arg GetSpaceParticipantsParams) ([]*GetSpaceParticipantsRow, error) {
	query := `
		SELECT sp.*, u.username, u.full_name, u.avatar_url
		FROM space_participants sp
		JOIN users u ON sp.user_id = u.id
		WHERE sp.space_id = $1 AND sp.left_at IS NULL
		ORDER BY sp.joined_at ASC
	`
	rows, err := q.db.QueryContext(ctx, query, arg.SpaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var results []*GetSpaceParticipantsRow
	for rows.Next() {
		var row GetSpaceParticipantsRow
		if err := rows.Scan(
			&row.SpaceParticipant.SpaceID, &row.SpaceParticipant.UserID,
			&row.SpaceParticipant.Role, &row.SpaceParticipant.Status,
			&row.SpaceParticipant.JoinedAt, &row.SpaceParticipant.LeftAt,
			&row.SpaceParticipant.Muted, &row.SpaceParticipant.IsHost,
			&row.Username, &row.FullName, &row.AvatarURL,
		); err != nil {
			return nil, err
		}
		results = append(results, &row)
	}
	return results, rows.Err()
}

// IsUserInSpace checks if a user is in a space.
func (q *Queries) IsUserInSpace(ctx context.Context, spaceID, userID string) (bool, error) {
	query := `SELECT EXISTS(SELECT 1 FROM space_participants WHERE space_id = $1 AND user_id = $2 AND left_at IS NULL)`
	var exists bool
	err := q.db.QueryRowContext(ctx, query, spaceID, userID).Scan(&exists)
	return exists, err
}